### ISSUE TITLE
Steelseries 300 black feedback (works)

### ISSUE THREAD

**Issue by cmol** [flozz/rivalcfg#1]
Hi

So I've been able to set the colours of the wheel and logo (though I tried turning them off which didn't work), as well as the different light effects.

Also, the refresh rate is settable, but I don't really know how to test it, the same with the presets for sensitivity. If you have some tests I can do, let me know!

And thank you! :)

**Comment by flozz** [comment]
Hello,

Thank you for your feedback.

So the working options are:

* `--logo-color`,
* `--logo-light-effect`,
* `--wheel-color`,
* `--wheel-light-effect`

> though I tried turning them off which didn't work

How you tried to turn them off? with the following command?

    rivalcfg --logo-color=black --wheel-color=black

> Also, the refresh rate is settable, but I don't really know how to test it, the same with the presets for sensitivity

For the sensibility presets, an easy way to test it is to 

* set a very low value: `rivalcfg --sensitivity1=250 --sensitivity2=250`
* if it worked, the cursor should become very slow
* then set a very high value `rivalcfg --sensitivity1=6000 --sensitivity2=6000`
* if it worked, the cursor will move quickly

For the refresh rate, it's hard to check if it works, I think the only way to do it is to spy the USB bus, but it is not a very simple thing to do...

Thank you again for your feedback! :)

**Comment by cmol** [comment]
Hi again

I had not tried supplying "black" as an argument, but that worked and the mouse goes black. In general I've tried using the rgb codes, but it seems like all values below `0x0a` (like `000009`) raises a value error:

    Traceback (most recent call last):
      File "/usr/local/bin/rivalcfg", line 9, in <module>
        load_entry_point('rivalcfg==2.2.0', 'console_scripts', 'rivalcfg')()
      File "/usr/local/lib/python2.7/dist-packages/rivalcfg/cli.py", line 171, in main
        getattr(mouse, option)(value)
      File "/usr/local/lib/python2.7/dist-packages/rivalcfg/rival_mouse.py", line 86, in _handler_rgbcolor
        raise ValueError()
    ValueError

The sensitivity settings works as you described with very slow or insanely fast motions.

Anything else you want tested? :)

**Comment by flozz** [comment]
Hi,

Thank you for your quick answer.

> I've tried using the rgb codes, but it seems like all values below 0x0a (like 000009) raises a value error

Oops, that's a bug in my implementation, `rivalcfg -c 099999` will crash the same way... I will fix this tomorrow :)

> The sensitivity settings works as you described with very slow or insanely fast motions.

Yeah \o/

> Anything else you want tested? :)

No, I think everything is ok, I will remove the `experimental` flag for this mouse.

Thank you again for your tests! :D

**Comment by cmol** [comment]
Great!

Let me know if something shows up. I'll be happy to test something out :)

**Comment by flozz** [comment]
the issue with the color parsing is fixed in the version **2.3.0**, and I removed the `experimental` flags. Thank you for your feedbacks! :)
