### ISSUE TITLE
rival 100 rgb

### ISSUE THREAD

**Issue by anarchygod** [flozz/rivalcfg#100]
the rivalcfg -c --color=COLOR command does not work. any suggestions?

**Comment by flozz** [comment]
Hello

* Is there any error message that can help?

* Also, you must use the `-c` OR `--color` option, not both. Example:

    rivalcfg -c red
    rivalcfg --color=aqua
    rivalcfg --color=00ff00

:)

**Comment by flozz** [comment]
I assume this problem is solved as there is no response. Please reopen it if it is not the case. :)
