### ISSUE TITLE
Rival 310 PUBG Edition

### ISSUE THREAD

**Issue by casual-E** [flozz/rivalcfg#109]
After following instructions and a seemingly successful install, running rivalcfg with any option gives me the output rivalcfg:command not found.  Any ideas what went wrong?

**Comment by casual-E** [comment]
Just needed a restart.

**Comment by flozz** [comment]
I do not know why a restart was needed but if it works... :D

**Comment by casual-E** [comment]
On second note, I have a SteelSeries Rival 310 PUBG Edition (ID = 1038:1736).  This mouse is not listed as compatible, but I took a chance because the only difference is the color compared to the regular Rival 310. I first tried normal commands for Rival 310, and then I tried to load the profile for RIval 310 and write to 1038:1736, but it did not work.

adam@Adam-PC:~$ RIVALCFG_PROFILE=1038:1720 RIVALCFG_DEVICE=1038:1736 rivalcfg -c black
[DEBUG] Rivalcfg 3.11.0
[DEBUG] Python version: 2.7.17
[DEBUG] OS: Linux
[DEBUG] Forced profile: 1038:1720
[DEBUG] Targeted device: 1038:1736
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 310 (Experimental) (1038:1720)
  * error: Unable to find the requested device: 1038:1720:00

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

[DEBUG] Selected mouse: None
Usage: rivalcfg [options]

rivalcfg: error: no such option: -c

Any suggestions?

**Comment by flozz** [comment]
Please open this as a new issue, I will add the support for your mouse ;)

**Comment by flozz** [comment]
Released iin **rivalcfg v3.12.0**. 

Thank you for the report, and welcome to Github ;)

**Comment by casual-E** [comment]
Thank you for the great support.  I found the following with 3.12.0 : 

adam@Adam-PC:~$ lsusb | grep Steel
Bus 001 Device 008: ID 1038:1736 SteelSeries ApS 

adam@Adam-PC:~$ rivalcfg
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 310 PUBG Edition (Experimental) (1038:1736)
  * error: open failed

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.
...

Any suggestion?

**Comment by flozz** [comment]
The udev rules are probably not up to date.

Try to copy the content of [this file](https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules) to `/etc/udev/rules.d/99-steelseries-rival.rules`

and then tel udev that you updated the rules with the following command:

    sudo udevadm trigger

It should work then :)

**Comment by casual-E** [comment]
Thank you, it now works.
