### ISSUE TITLE
Macro support

### ISSUE THREAD

**Issue by CPAllianceP** [flozz/rivalcfg#11]
Does it support macros for Rival 100 mouse?

**Comment by flozz** [comment]
Hello,

Currently, rivalcfg only supports hardware features of the mouse. As macros are a software feature of the Steelseries Engine 3, they are not supported.

On Linux, there is some generic tools to make mouse macros that not depends on a specific mouse model, like [Xnee][] and [XMacro][]. Maybe they can help you.

[Xnee]: https://www.gnu.org/software/xnee/
[XMacro]: http://xmacro.sourceforge.net/

**Comment by CPAllianceP** [comment]
Ok, thanks.
