### ISSUE TITLE
Manjaro Linux pip install

### ISSUE THREAD

**Issue by electricsurge31** [flozz/rivalcfg#110]
Hi, I am fairly new to Linux and have definitely never used anything from Pypi or pip. I have the latest version of Manjaro Linux with kernel 5.5. Every piece of documentation i have found regarding pip install has stated not to run pip under "sudo pip install" due to pacman having conflicts or creating a security risk by doing so. I understand in your documentation it is stated to run as root, but I do not feel like switching user to the root user and installing is the correct procedure either. 
I just wanted some clarification on the procedure here.
I have a Rival 650 that i just purchased and would really love to get this going!

Also, I apologize if this is the incorrect location to be posting this sort of question, I couldn't find a comments location or anything.
I looked through all of the past issues that i thought may be able to answer my questions, but i am not sure, so if i missed one i'd be happy to take a look!

I really appreciate the help!

**Comment by FFY00** [comment]
The whole point of not using `sudo pip install` is to not install as root, installig directy as root is the same thing.

**Comment by electricsurge31** [comment]
Okay, i appreciate the quick response. Seems like my safest best is the AUR. I will go down that route.

Thank you!

**Comment by flozz** [comment]
The best way to install rivalcfg is to use the package for your distribution, when it exists.

When using pip, root is needed to install the udev rules file (`/etc/udev/rules.d/99-steelseries-rival.rules`), but you can copy it manually. 😁️

Anyway, the Rival 650 is not supported by rivalcfg yet, sorry 😔️
