### ISSUE TITLE
error: open failed

### ISSUE THREAD

**Issue by cdillonwilliams** [flozz/rivalcfg#116]
Rival 300, just installed on Ubuntu 20.04. Keep getting the error 'open failed'. This error does not appear in a dry run. I tried unplugging/replugging and restarting. The mouse is plugged into a USB-C port on my laptop via an adapter.
Here is the debug ouput:

$ RIVALCFG_DEBUG=1  rivalcfg
[DEBUG] Rivalcfg 3.12.0
[DEBUG] Python version: 3.8.2
[DEBUG] OS: Linux
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 300 (1038:1710)
  * error: open failed

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

[DEBUG] Selected mouse: None
Usage: rivalcfg [options]

Options:
  --version   show program's version number and exit
  -h, --help  show this help message and exit
  -l, --list  print compatible mice and exit

Please report any bug on Github: https://github.com/flozz/rivalcfg/issues

**Comment by flozz** [comment]
Hello,

Can you check that the following file exists `/etc/udev/rules.d/99-steelseries-rival.rules`?

----

If not, try the following commands:

    sudo wget -O /etc/udev/rules.d/99-steelseries-rival.rules
    sudo udevadm trigger

And it should work then.

----

If the file already exists, we will have to investigate to find what happen... 😅️

**Comment by cdillonwilliams** [comment]
Wow, I should have tried this!! 🤦 It worked. Thanks for the help and the quick reply.

**Comment by flozz** [comment]
No problem, welcome to Github 😉️
