### ISSUE TITLE
Hi i have ubuntu 16.04 and have installed everything according to the docs but still its says rivalcfg command not found

### ISSUE THREAD

**Issue by shpleef** [flozz/rivalcfg#12]
![image](https://cloud.githubusercontent.com/assets/16339855/19417454/ccda6812-93ad-11e6-92ab-2193e7892063.png)

**Comment by shpleef** [comment]
im a noob in linux!

**Comment by flozz** [comment]
Hello,

In order to install rivalcfg, you have to run the command as root:

    sudo pip install .
