### ISSUE TITLE
Support for Rival 3

### ISSUE THREAD

**Issue by abeauvisage** [flozz/rivalcfg#120]
Hi, just got a new Rival 3 mouse (https://steelseries.com/gaming-mice/rival-3).
Here are the corresponding vendor_id and product_id: 
`Bus 007 Device 002: ID 1038:1824 SteelSeries ApS SteelSeries Rival 3`
I added it to the udev rules and tried to use the following command:
`RIVALCFG_DEBUG=1 RIVALCFG_PROFILE=1038:1384 RIVALCFG_DEVICE=1038:1824 python -m rivalcfg --color=red`
Which returns:

```
[DEBUG] Rivalcfg 3.12.0
[DEBUG] Python version: 3.8.2
[DEBUG] OS: Linux
[DEBUG] Forced profile: 1038:1384
[DEBUG] Targeted device: 1038:1824
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival (1038:1384)
  * error: Unable to find the requested device: 1038:1384:00

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

[DEBUG] Selected mouse: None
Usage: rivalcfg [options]

__main__.py: error: no such option: -c
```

However when updating the `product_id` field in rivalcfg/profiles/rival.py the mouse seems to be recognised, even though the settings are wrong:

```
[DEBUG] Rivalcfg 3.12.0
[DEBUG] Python version: 3.8.2
[DEBUG] OS: Linux
[DEBUG] Selected mouse: <Mouse SteelSeries Rival (1038:1824:00)>
[DEBUG] Mouse._device_write [wValue]: 02 00
[DEBUG] Mouse._device_write   [data]: 08 01 FF 00 00
An error occured when updating mouse settings!
```

I am ready to help but have no idea how to find the right settings.

**Comment by flozz** [comment]
Hello,

The support for the Rival 3 has already been implemented. It is currently in the `rivalcfg4.0` development branch. See #111 for more information.

You can try it by cloning this repository and installing rivalcfg from the `rivalcfg4.0` branch:

```
git clone https://github.com/flozz/rivalcfg.git
cd rivalcfg
git checkout rivalcfg4.0
sudo pip install .
```

And then you will have to update udev rules:

```
sudo rivalcfg --update-udev
```

:)

**Comment by abeauvisage** [comment]
Ah yes, I didn't see it was already implemented in `rivalcfg4.0`. Just tried it and it works like a charm :)

Thanks, that's an awesome project!
