### ISSUE TITLE
Request: --light-effect option to disable light

### ISSUE THREAD

**Issue by sageTF2** [flozz/rivalcfg#128]
I'm not sure if I just missed it but I believe theres currently no option to disable the light from the mouse altogether like in the original SteelSeries driver. I'm using a Rival 110, in case thats an issue.

**Comment by flozz** [comment]
Hello,

When you select the option to turn off the light in the SSE3, it just sends the black color to the mouse. With Rivalcfg, you can do it with the following command:

    rivalcfg --color black

:)

**Comment by flozz** [comment]
I just updated this question in the FAQ: https://flozz.github.io/rivalcfg/faq.html#how-can-i-turn-the-lights-off

I close this issue but do not hesitate to post a message if you have further questions :)

**Comment by batkor** [comment]
Thanks.
Disable RGB for SteelSeries Rival 3:
`rivalcfg --logo-color=black --strip-top-color=black --strip-middle-color=black --strip-bottom-color=black`
