### ISSUE TITLE
Improvement : Add a way to get values

### ISSUE THREAD

**Issue by dguihal** [flozz/rivalcfg#13]
It could be cool to be able to get current settings from mouse (if possible). As far as I can see the tool (which is great) is only able to set values

**Comment by flozz** [comment]
Hello,

I found no way to read values on the mouse.

In my observation (when I reverse  engineered the mouse), the SteelSeries Engine 3 saved the last known configuration on the computer for later use.

**Comment by dguihal** [comment]
Thanks for the reponse, it's a shame but you can't do anything about it.
