### ISSUE TITLE
AUR installation

### ISSUE THREAD

**Issue by HanaO00** [flozz/rivalcfg#141]
Hello, i have this error with the AUR package (git version)

`install: impossible d'évaluer 'doc/rival-spec.md': Aucun fichier ou dossier de ce type
==> ERREUR : Une erreur s’est produite dans package().
    Abandon…
:: Unable to build rivalcfg-git - makepkg exited with code: 4
=>> Try again? [y/N]: 
`

**Comment by flozz** [comment]
Hello, 

The package is not up to date, I will try to update it :)

**Comment by fedebenelli** [comment]
Yes, please do! I'm having the same error :(

running install_scripts
Installing rivalcfg script to /home/ruther/.cache/yay/rivalcfg/pkg/rivalcfg/usr/bin
install: cannot stat 'doc/rival-spec.md': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
error making: rivalcfg

**Comment by GoliathLabs** [comment]
Good day :)
I'm the maintainer of rivalcfg on the AUR. Sorry for jumping into this issue so late :/
I've updated the PKGBUILD. So things should (hopefully) work again. You might also propose changes to it here or in the comments section on the AUR. I'm willing to make your experience as smooth as possible :)

Cheers,
Felix

**Comment by GoliathLabs** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/?h=rivalcfg
(the git tree of the current pkgbuild)

**Comment by flozz** [comment]
Thank you very much @GoliathLabs ! :D

I tried to update the `rivalcfg-git` package as well as it seems I am the maintainer of it... Can someone test it works (if not, I will take some time to install a new Archlinux VM)?

**Comment by flozz** [comment]
@GoliathLabs I forget a thing, can you update the package description, as this software now configures any SteelSeries mice, not only the Rival?

I updated the description of `rivalcfg-git` to `"CLI tool and Python library to configure SteelSeries gaming mice"` if it can help :)

**Comment by fedebenelli** [comment]
@GoliathLabs I've tried installing `rivalcfg-git` and it worked fine for me!

**Comment by flozz** [comment]
@fedebenelli ok cool, so I close the issue.

Thank you again @GoliathLabs for the update of the `rivalcfg` package, it helped me for the `rivalcfg-git` too :D

**Comment by GoliathLabs** [comment]
No problem :)
