### ISSUE TITLE
Mouse Button Support For Rival 100

### ISSUE THREAD

**Issue by Borsayt** [flozz/rivalcfg#142]
Are u planning to add rival 100 mouse button macros support or is it possible?

**Comment by flozz** [comment]
Hello!

* Button mapping is not supported onboard by the Rival 100 (it is a SteelSeries Engine 3 software feature for this device)
* On all mice, macros is always a software feature provided by the SSE3

So this will not be supported by Rivalcfg (it supports only hardware features)

Maybe you will find useful information in this thread to create macros on Linux:

* https://askubuntu.com/questions/752325/any-macro-recorder-programs-availiable

:)

**Comment by Borsayt** [comment]
Thank you, my left mb is broken so im trying to add mb1 to macro button but i cant figure out how i do it :+1:

**Comment by flozz** [comment]
If you are using X11 maybe this can help : https://unix.stackexchange.com/questions/192191/remap-mouse-button-8-browser-forward-to-mouse-button-2-middle-click-on-r

but I cannot help more I think :(

**Comment by Borsayt** [comment]
It workedd !!!! Thank you :)

**Comment by flozz** [comment]
I am happy it helped. So I close the issue :smile:
