### ISSUE TITLE
Support for ROCCAT Kone EMP mouse

### ISSUE THREAD

**Issue by LittleWhite-tb** [flozz/rivalcfg#143]
Hello,

I have recently read this [blog post](https://blog.flozz.fr/2020/08/24/rivalcfg-comment-jai-cree-un-peu-par-hasard-cet-outil-de-configuration-pour-les-souris-steelseries/) and I am wondering if it would be interesting to support more mouses, even some from other constructors.
I don't see why it would not be possible. Attached to the ticket, some reverse on the ROCCAT Kone EMP mouse.
```
lsusb -d 1e7d:
Bus 001 Device 005: ID 1e7d:2e24 ROCCAT 
```
[Doc-KoneEMP-USB-Config.txt](https://github.com/flozz/rivalcfg/files/5250154/Doc-KoneEMP-USB-Config.txt)

**Comment by flozz** [comment]
Hello,

This software is dedicated to SteelSeries devices.

Rivalcfg was architectured around the SteelSeries devices and it will not be that easy to support other constructor mouse. For example, in the data you provided from your ROCCAT mouse we can see that all the configurations are sent to the device in the same packet, where SteelSeries devices have different commands for each setting (and so, this software is made to work with different commands for each parameters).

Also it is already a big challenge to support all the ~70 mice from SteelSeries. It is not the goal of this software to support more.

Finally, the name of this software came from the SteelSeries Rival mouse... it makes no sens to support devices from other constructors without changing its name.

----

So I will not support ROCCAT devices in this software, but there is other things you can do:

There is an other software dedicated to gaming mice that aims to support devices from any constructor. It is called [libratbag](https://github.com/libratbag/libratbag) (and its GUI is called [Piper](https://github.com/libratbag/piper)). Maybe you can work with this project.

Also, there is already a Linux software dedicated to ROCCAT devices:

* http://roccat.sourceforge.net/
* An other doc about this software: https://doc.ubuntu-fr.org/clavier_souris_roccat

Finally, if the two solutions above do not suit your needs, you can write your own tool (do not hesitate to ask if you need some help with that ;) )

----

I hope my answer can be helpful to you :)

**Comment by LittleWhite-tb** [comment]
Thank you for the very complete answer. I did not know about libratbag.
I hope you the best for your project ;). Keep up the good work !
