### ISSUE TITLE
Adjustable Debounce time?

### ISSUE THREAD

**Issue by Zilli341** [flozz/rivalcfg#144]
Is the debounce time hard-coded into the firmware or is it possible to make it adjustable? It would be helpful if you have double clicking issue or if you intentionally want your mouse to register double clicks (for minecraft pvp as an example)

**Comment by flozz** [comment]
I think it is a software feature of the SSE3, but I can take a look. Which mouse do you have?

**Comment by Zilli341** [comment]
I have a rival 600

**Comment by flozz** [comment]
Hum I can check on the Rival 650 then, it should be close

**Comment by Syndric** [comment]
Also needing functionality for the same purpose on the Sensei 310.

**Comment by flozz** [comment]
I did not found any debouce time setting in the SteelSeries Engine...

And I found only few things about this on the internet :/

* http://blog.guntram.de/?p=16

**Comment by Syndric** [comment]
It seems to be a part of the mouse firmware and not a normal settable option.

Sensei/Rival 310 are the only mouses I know of where debounce time can be removed by force updating mouse firmware with engine 3.10.12 (in case anyone is wondering).

**Comment by Zilli341** [comment]
The Rival 600 debounce time can also be greatly decreased by using engine 3.11.13 and downgrading the firmware.

**Comment by flozz** [comment]
I close this issue as there is no more activity on it. :)
