### ISSUE TITLE
Rival 3 on updated firmware no longer supported 

### ISSUE THREAD

**Issue by nagadevshanmukh** [flozz/rivalcfg#147]
After updating the firmware (0.37.0.0) on Rival 3, rivalcfg no longer seems to recognize it (1038:184c) on Linux. Have you come across this?

**Comment by flozz** [comment]
Hello,

 I cannot find any devices with `1038:184c` id. Can you copy the entire line from the `lsusb` command. :)

**Comment by nagadevshanmukh** [comment]
Appreciate the quick response - here is the full text -

Bus 001 Device 002: ID 1038:184c SteelSeries ApS SteelSeries Rival 3

As far as I can tell, this happened after I moved to Engine 3.18.10 from 30.18.8 and updated firmware. Hope this helps.

**Comment by flozz** [comment]
You are right, they changed the USB descriptor in the new firmware.

Can you change the `product_id` in [rivalcfg/devices/rival3.py](https://github.com/flozz/rivalcfg/blob/master/rivalcfg/devices/rival3.py#L11) and try if it works (do not hesitate if you need some help, I can make a test branch for this.). Note that after this change you will probably need to run the `rivalcfg` command as root as udev rules will not be up to date

:)

**Comment by nagadevshanmukh** [comment]
Thanks! Worked as expected and appreciate your help :-)

**Comment by flozz** [comment]
Ok so I will add this `product_id` to rivalcfg :)

**Comment by flozz** [comment]
It is on `master`, it will be released soon in v4.2.0. Thank for the report :)

**Comment by nagadevshanmukh** [comment]
Thanks for the update! Will this also update the udev rules so running as root won't be needed?

**Comment by flozz** [comment]
Yes you will be able to update the udev rules with this release :)
