### ISSUE TITLE
Support for acceleration / deceleration?

### ISSUE THREAD

**Issue by squiil** [flozz/rivalcfg#149]
Hey thank you so much for this, and thank you for making it easy to follow for a noob like me! Im just wondering if the accel/decel feature the steelseries engine has will ever be added? I have a Rival 300 series.

Thanks!

**Comment by flozz** [comment]
Hello,

This cannot be implemented in Rivalcfg : it is a software feature, not an hardware one. This kind of parameter should be configurable in the settings of your desktop environment on Linux.

When using GNOME, the setting can be found in GNOME Tweaks:

![image](https://user-images.githubusercontent.com/971438/101285862-e5f5db00-37e7-11eb-8126-bdea25828673.png)

I do not know if there is more advanced setting available elsewhere. :)
