### ISSUE TITLE
Permission Denied: "IOError: [Errno 13] Permission denied: u'/dev/hidraw0'"

### ISSUE THREAD

**Issue by berkiyo** [flozz/rivalcfg#15]
Hi there!

Recently purchased a Rival 100 and it has been great! I have used your software to configure my mouse and it worked flawlessly. Also finding this software specifically made for this mouse made me super happy as I only use Linux.

One day, I wanted to change the DPI of the mouse and the colour unfortunately none of these worked. I got the following error in the screenshot.
![1234](https://cloud.githubusercontent.com/assets/16160502/21580551/79284bde-d053-11e6-8bd6-902649f83c2f.png)

No matter what I do, it won't work! This problem persists in Arch Linux 4.8.13 as well as my current OS; Ubuntu MATE 16.04 with 4.4 LTS kernel.

Do you have a solution to this issue? I really want to use your software but it won't work :(

Kind Regards

**Comment by flozz** [comment]
Hello,

Does the file `/etc/udev/rules.d/99-steelseries-rival.rules` exists?

If not, create it and put this content into it ([original file here](https://github.com/flozz/rivalcfg/blob/master/rivalcfg/data/99-steelseries-rival.rules)):
```
# SteelSeries Rival 100
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="1702", MODE="0666"
```
then run the following command:

    udevadm trigger

**Comment by FriXion65** [comment]
Hello, I am novice on Ubuntu, thus I do not know much. I had the problem "IOError: [Errno 13] Permission denied: u '/dev/hidraw0" and thus I fell on this tutorial. Having to try during more than one hour how to create the missing file, I have wanted to execute the order udevadm trigger ". Unfortunately nothing occurs and when I try to change my sensibility the problem is always the same.

What do I have to make or I badly did something?

Thank you in advance for your answer.

P.S.: I am French and I used an automatic translator, thus I apologize for susceptible present problems of translation.

**Comment by flozz** [comment]
**Version Française en fin de message ↓↓**

---
### English version

Hello,

First you have to download the [99-steelseries-rival.rules][https://github.com/flozz/rivalcfg/blob/master/rivalcfg/data/99-steelseries-rival.rules] file and to put it in the `/etc/udev/rules.d/` folder. This can be done with the following command:

    sudo wget -O /etc/udev/rules.d/99-steelseries-rival.rules https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules

Then you have to execute the following command to tell udev to update its rules:

    udevadm trigger

---
### French version

Bonjour,

Vous devez d'abord commencer par télécharger le fichier [99-steelseries-rival.rules][https://github.com/flozz/rivalcfg/blob/master/rivalcfg/data/99-steelseries-rival.rules] puis le placer dans le dossier `/etc/udev/rules.d/`. Ceci peut être fait avec la commande suivante :

    sudo wget -O /etc/udev/rules.d/99-steelseries-rival.rules https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules

Une fois ceci fait, il faut exécuter la commande suivante pour indiquer à udev de mettre à jours ses règles :

    udevadm trigger

**Comment by FriXion65** [comment]
Merci beaucoup pour votre aide. C'est bon, mon problème est résolu ! Et encore merci d'avoir développé ce logiciel, il remplace parfaitement Steel Series Engine 3 sur Windows.
