### ISSUE TITLE
Support for "repeat while pressed" feature

### ISSUE THREAD

**Issue by tominkki** [flozz/rivalcfg#150]
Adding support for repeat while pressed functionality in button mapping would be great feature. Especially when mapping buttons for scroll down/up. Without repeat while pressed those functionalities are pretty much useless in many use cases.

Is this feature possible to implement for all supported hardware?

**Comment by flozz** [comment]
Hello!

No, this feature cannot be implemented in Rivalcfg: this is a SSE3 feature, it is not handled by the hardware, sorry :)
