### ISSUE TITLE
Map button to a key combo

### ISSUE THREAD

**Issue by hermitpurple746** [flozz/rivalcfg#151]
Is it possible to assign multiple keys to a mouse button? For example Button 5 = LeftCtrl + C to copy

**Comment by flozz** [comment]
I forgot to answer you question, sorry ^^'

Technically, it **seems** possible on some devices but this is never used by the SteelSeries Engine (when you setup a combo, it does it by software), so I will probably not support this in Rivalcfg, sorry.
