### ISSUE TITLE
Factory reset is wrong on sensei TEN

### ISSUE THREAD

**Issue by MCMic** [flozz/rivalcfg#155]
After testing rivalcfg, I used rivalcfg -r to get back to original state, but it was way faster.

It seems the default value for -c is not the factory default. I guess the duration is wrong, I tried with 10000 instead of 1000 and it seems closer to factory default.

**Comment by flozz** [comment]
I will check (next week) if I can reproduce the issue on my Sensei TEN. :)

**Comment by ali1234** [comment]
I can confirm this. The animation speed is presumably milliseconds and the Windows software says the default speed is 10 seconds, so 10000 would be right. Also the default factory config has five sensitivity settings, not two. They are 400, 800, 1200, 2400, 3200, according to Windows - rivalcfg sets 800, 1600.
