### ISSUE TITLE
Feature: Scrool speed Rival110

### ISSUE THREAD

**Issue by klebann** [flozz/rivalcfg#162]
Hi,
I installed this program because I want to be able to change mouse scrool speed on ubuntu18.04
After I pluged my mouse to ubuntu I recognized that the scrool speed is very slow comparing to Windows10.
There is no scrool acceleration when you scrool the mouse faster.
Also clicking middle click on mouse it doesn't open AutoScroll.

Avaible commands for Rival 110:
```
SteelSeries Rival 110 Options:
  -s SENSITIVITY1, --sensitivity1 SENSITIVITY1
                        Set sensitivity preset 1 (DPI) (from 200 to 7200,
                        default: 800)
  -S SENSITIVITY2, --sensitivity2 SENSITIVITY2
                        Set sensitivity preset 2 (DPI) (from 200 to 7200,
                        default: 1600)
  -p POLLING_RATE, --polling-rate POLLING_RATE
                        Set polling rate (Hz) (values: 125, 250, 500, 1000,
                        default: 1000)
  -c COLOR, --color COLOR
                        Set the mouse LED color (e.g. red, #ff0000, ff0000,
                        #f00, f00, default: #FF1800)
  -e LIGHT_EFFECT, --light-effect LIGHT_EFFECT
                        Set the light effect (values: steady, breath, 1, 2, 3,
                        4, default: steady)
  -b BTN6_MODE, --btn6-mode BTN6_MODE
                        Set the mode of the button under the wheel (values:
                        dpi, os, default: dpi)
  -r, --reset           Reset all settings to their factory default

```

Adding scrool speed config should be a nice feature to have.

**Comment by flozz** [comment]
Hello,

>  There is no scrool acceleration when you scrool the mouse faster.

SteelSeries mice do not have any configurable wheel speed / acceleration option. Rivalcfg only support configuring features that are supported by the hardware.

The wheel speed (and probably acceleration?) can be configured at the OS level, on Linux there is tools available for this (at least on X11, I do not know for Wayland). This article may be a good place to start: https://mintguide.org/other/643-setup-the-mouse-scroll-wheel-speed.html

>  Also clicking middle click on mouse it doesn't open AutoScroll.

On Linux, this feature is supported only by some applications like Firefox. It can be enabled / disabled in the application settings. Example for Firefox (sorry my Firefox is in French):

![image](https://user-images.githubusercontent.com/971438/109535107-7298f800-7abc-11eb-8bd5-6d6b3027e8d5.png)

**Comment by klebann** [comment]
Ohh okey, thanks for your investigation.

I'm using google chrome and I found there plugin called "Auto scroll", which is very useful.

Yes, you have right, I installed original driver on Windows and it doesn't have an option to change scroll speed.

I thought that mouse have scroll acceleration because it is significant faster on Windows.

Thanks for your help. I'm closing this issue.

**Comment by klebann** [comment]
Although your program is very useful. I can adjust mouse sensitivity and colour of led.
