### ISSUE TITLE
open failed on every command

### ISSUE THREAD

**Issue by Siamaster** [flozz/rivalcfg#163]
rivalcfg --version
 
Traceback (most recent call last):
  File "/usr/local/bin/rivalcfg", line 11, in <module>
    load_entry_point('rivalcfg==4.3.0', 'console_scripts', 'rivalcfg')()
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg/__main__.py", line 52, in main
    mouse = get_first_mouse()
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg/__init__.py", line 29, in get_first_mouse
    product_id=plugged_devices[0]["product_id"])
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg/mouse.py", line 30, in get_mouse
    hid_device = usbhid.open_device(vendor_id, product_id, profile["endpoint"])
  File "/usr/local/lib/python3.6/dist-packages/rivalcfg/usbhid.py", line 93, in open_device
    device.open_path(path)
  File "hid.pyx", line 74, in hid.device.open_path
OSError: open failed

**Comment by flozz** [comment]
Hello,

Can you give me the result of the `rivalcfg --print-debug` command? :)

**Comment by umithyo** [comment]
Hello, @flozz I'm having the same issue. Here is the result of `rivalcfg --print-debug`:
```
RIVALCFG
========
Version: 4.3.0
udev rules installed: True
udev rules up to date: True
Installation path: /usr/local/lib/python3.8/dist-packages/rivalcfg

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-5.8.0-50-generic-x86_64-with-glibc2.29
Version: #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021
Distribution issue: Ubuntu 20.04.2 LTS \n \l

PYTHON
======
Python version: 3.8.5
HIDAPI version: 0.10.1

PLUGGED STEELSERIES DEVICES ENDPOINTS
=====================================
1038:12b3 | 03 |  (firmware v0)
1038:1729 | 00 |  (firmware v0)
1038:1729 | 01 |  (firmware v0)
```

**Comment by flozz** [comment]
Hello,

* Can you check that the `/etc/udev/rules.d/99-steelseries-rival.rules` is present?
* If you just installed Rivalcfg, sometime unplugin/repluging fix the issue, and sometime a reboot is required.
* If you cannot reboot now, you you can also try running `rivalcfg` as root

**Comment by umithyo** [comment]
Using `sudo rivalcfg` worked. I don't know why I haven't done that. Thanks!

**Comment by glyph** [comment]
I just started haivng this problem as well, on macOS.

If I repeat the command 5-10 times, I will eventually get a response.  Sometimes I'll get an `open failed` traceback, sometimes I'll get "Unable to get the battery level".

**Comment by flozz** [comment]
I close this issue as the problem was solved :)
