### ISSUE TITLE
Rival 106 not detected

### ISSUE THREAD

**Issue by SeanyC** [flozz/rivalcfg#168]
I have a Rival 106 plugged in, but the software does not seem to be able to configure it, and it does not show up in the debug command.

```
RIVALCFG
========
Version: 4.3.0
udev rules installed: True
udev rules up to date: True
Installation path: /usr/local/lib/python3.8/dist-packages/rivalcfg

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29       
Version: #1151-Microsoft Thu Jul 22 21:05:00 PST 2021
Distribution issue: Ubuntu 20.04.2 LTS \n \l

PYTHON
======
Python version: 3.8.10
HIDAPI version: 0.10.1

PLUGGED STEELSERIES DEVICES ENDPOINTS
=====================================
```

**Comment by flozz** [comment]
Hello, 

Are you trying to use the software from WSL/WSL2 on Windows? 

If yes, it will probably not work (at least I never tested such a configuration...). But Rivalcfg can work natively on Windows, so you can install it using a Python distribution for Windows instead of WSL. 

:)

**Comment by SeanyC** [comment]
I suppose you've seen this before

output after install to windows directly and not WSL

```
RIVALCFG
========
Version: 4.3.0
Installation path: c:\users\sean\appdata\local\programs\python\python39\lib\site-packages\rivalcfg

OPERATING SYSTEM
================
OS: Windows
PYTHON
======
Python version: 3.9.6
HIDAPI version: 0.10.1

PLUGGED STEELSERIES DEVICES ENDPOINTS
=====================================
1038:1816 | 00 | SteelSeries Rival 106 Gaming Mouse (firmware v0)
1038:1816 | 01 |  (firmware v0)
1038:1816 | 01 |  (firmware v0)
1038:1816 | 01 |  (firmware v0)
```

**Comment by flozz** [comment]
When I saw "Linux" and "Microsoft" on the same line, I thought to WSL :) 

I hope it work with the native instalation 👍

**Comment by SeanyC** [comment]
Working great now, thanks for your help!
