### ISSUE TITLE
Rival 100 Dota 2 Edition (retail version) 1038:170b

### ISSUE THREAD

**Issue by B-greg** [flozz/rivalcfg#17]
Hi, 
I buy a special edition of the rival 100 but its not detected by the programs.
$ lsusb
Bus 003 Device 003: ID 1038:170b SteelSeries ApS 

$ rivalctl
E: No compatible mouse found. Type 'rivalcfg --help' for more informations.

$ DEBUG_DRY=true DEBUG_MOUSE=1038:170b rivalcfg
[DEBUG] Debugging rivalcfg 2.4.3...
[DEBUG] Python 2.7.12
[DEBUG] Dry run enabled
[DEBUG] Debugging mouse profile 1038:170b
[DEBUG] No mouse profile found
E: No compatible mouse found. Type 'rivalcfg --help' for more informations.

This mouse have something really different than the normal rival 100?

**Comment by flozz** [comment]
Hello,

Your mouse have maybe not the same set of commands than the original Rival 100 but you can try it out:

    DEBUG_MOUSE=1038:1702 rivalcfg -c red

Here I used the product Id of the original Rival 100 (`1702`)

**Comment by B-greg** [comment]
Hi,
I clone your project and change the rival100.py as follow:
`rival100 = {
    "name": "SteelSeries ApS",

    "vendor_id": "1038",
    "product_id": "170b",
    "hidraw_interface_number": 0,

    "command_before": None,
    "command_after": "save",
`

then there as my output:
$  rivalcfg -c blue 
E: The 'SteelSeries ApS' mouse is plugged in but the control interface is not available.

Try to:
  * unplug the mouse from the USB port,
  * wait fiew seconds,
  * and plug the mouse to the USB port again.

$ DEBUG_DRY=true DEBUG_MOUSE=1038:170b rivalcfg -c blue 
[DEBUG] Debugging rivalcfg 2.4.3...
[DEBUG] Python 2.7.12
[DEBUG] Dry run enabled
[DEBUG] Debugging mouse profile 1038:170b
[DEBUG] Mouse profile found: SteelSeries ApS
[DEBUG] _device_write: 05 00 00 00 FF
[DEBUG] _device_write: 09 00

I think the interface number change or the instructions values are not the sames

**Comment by flozz** [comment]
So this mouse needs to be reverse engineered to be supported, but I cannot do it (I do not own this mouse)

**Comment by B-greg** [comment]
Can you explain how you did this with your mouse? I will try with mine when i will get free time.
When i buy this mouse i think they only change the logo on the top, not change the hardware.

**Comment by flozz** [comment]
I wrote an article about that, but it is in french (maybe Google Translate can help):

http://blog.flozz.fr/2016-03-27/steelseries-rival-100-reverse-engineering-peripherique-usb/

**Comment by B-greg** [comment]
That fine I'm french. Thank you very much.
I'm quite busy right now for spend many time on it but i will send you back my results.

**Comment by B-greg** [comment]
Hi,
I make the revert reverse engineering linke your article, and the usb address are the same
`
# echo -en "\x05\x00\xFF\x00\x00" > /dev/hidraw0
`

and this
`
# echo -en "\x07\x00\x03" > /dev/hidraw0
`

work perfectly.
I will need to check the code if its a bad configuration with my mice.

**Comment by flozz** [comment]
Hello,

Maybe your issue was related to #21

Can you try again with **rivalcfg 2.5.1** (you will need to patch the `rival100.py` file with your mouse's produtId, as you already did before).

**Comment by flozz** [comment]
This mouse is the same than the rival 100, it will be supported soon

**Comment by flozz** [comment]
Update:

The support of this mouse was added to the `rivalcfg4.0` branch, It will be released with **Rivalcfg 4.0** :)
