### ISSUE TITLE
No actual change, Nothing is working here

### ISSUE THREAD

**Issue by ItamarX** [flozz/rivalcfg#18]
I Installed the script and ran it a few times but nothing is actually working.
I'm using Rival 300 on Arch linux, I also tried to debug - I got the same output as shown in the readme Debug section, but still - actual change on the mouse it self.

![deepinscreenshot20170211134641](https://cloud.githubusercontent.com/assets/15173282/22853501/cc6adf16-f04f-11e6-9c6a-74ae464974c7.png)

p.s.
I tried python2 aswell, no change

**Comment by flozz** [comment]
Hello,

It seems that SteelSeries released a new firmware with a new set of commands, that's maybe the issue you are encounter. See #5 for more informations.
