### ISSUE TITLE
How to flush updated mouse settings through the python API?

### ISSUE THREAD

**Issue by mvrozanti** [flozz/rivalcfg#180]
Hi, I was really glad to find this project, I recently got a Rival 300 and tinkered with the settings through the cli a bit and it worked great

Now I'm trying to use the Python API with the following script:

    import rivalcfg
    mouse = rivalcfg.get_first_mouse()
    mouse_settings = mouse.mouse_settings
    mouse_settings.set('z1_color', 'fff')
    mouse_settings.save()
    mouse.save()

And while I get no errors, the colors don't update. I read the docs but couldn't find a way to actually flush the changes. What am I missing here?

**Comment by mvrozanti** [comment]
After taking a look in the main file, I got it working like this:

    import rivalcfg
    mouse = rivalcfg.get_first_mouse()
    getattr(mouse, 'set_z1_color')('fff')

**Comment by flozz** [comment]
`mouse_settings` are just a way to read/save settings from/to the HDD (as we cannot read-back values from the device), not to communicate with the mouse. They can be useful to know the current state of the mouse (if it is only used on one machine and configured only with rivalcfg). :)
