### ISSUE TITLE
Request: Rival 5

### ISSUE THREAD

**Issue by daftinquisitor** [flozz/rivalcfg#181]
Device identification:

```
Bus 001 Device 002: ID 1038:183c SteelSeries ApS SteelSeries Rival 5
```

Product URL:

https://steelseries.com/gaming-mice/rival-5

SSE3 Screenshots:

I can add this later today, but I don't have them just yet.

I can also do the reverse-engineering steps if needed.

**Comment by flozz** [comment]
Hello,

There is already an opened issue for the Rival 5 → #165, let's continue there :)

> I can also do the reverse-engineering steps if needed.

It will be helpful: I do not own this device :D
