### ISSUE TITLE
thanks, it seems to work great on macOS

### ISSUE THREAD

**Issue by glyph** [flozz/rivalcfg#182]
I have been [pretty unhappy about SteelSeries' official software for quite some time](https://twitter.com/glyph/status/1516136388936167425) so when I saw this I immediately did a `pipx install rivalcfg` and was pleasantly surprised to see that it *did* work without any effort on my mac, at least to the trivial case of `rivalcfg --battery-level`.  Equally pleasantly surprised that `from rivalcfg import get_first_mouse; m = get_first_mouse(); print(m.battery)` was all I needed to do if I wanted to customize my own presentation of the info.

So, no problem here, just wanted to give a more detailed "thank you" beyond a star.

**Comment by flozz** [comment]
I am very happy that Rivalcfg was useful to you! Thank you for the feedback! :)
