### ISSUE TITLE
Is it possible to add LED brightness support for the Aerox 3 wireless ?

### ISSUE THREAD

**Issue by bokub** [flozz/rivalcfg#186]
Hi,

I can see that the Aerox 3 supports the `--led-brightness` option, but not the wireless option.

Do you think it could be added ?

I can build & test myself if you don't have the mouse

Thanks a lot for your work, it's really awesome :+1: !

**Comment by flozz** [comment]
Hello,

I had to remove this option to support dim timer without having to much development. You are already able to lower the brightness by setting a darker color.

For example:

* `FF0000` → red, full brightness
* `880000` → red, 50% brightness

**Comment by bokub** [comment]
Oh, I didn't think about that, thank you !
