### ISSUE TITLE
no-colors option

### ISSUE THREAD

**Issue by verdernel** [flozz/rivalcfg#19]
Hello,
I just find your nice program today, thank you/merci :)
I would like a option to disable lights - colors.
Maybe in the option --logo-light-effect we could do 
`rivalcfg --logo-light-effect 0`

I could do it, but i don't know yet how to. :D

**Comment by flozz** [comment]
Hello,

If you want to switch off the lights, you can set the black color to them:

    rivalcfg --color=black                             # rival 100
    rivalcfg --logo-color=black --wheel-color=black    # rival 300

**Comment by verdernel** [comment]
Oh my bad i didn't saw that on the docs.
Thank you that was exactly what I was searching.

**Comment by flozz** [comment]
You are right, I did not wrote anything about this in the doc. I will add this the next time I update this software :)
