### ISSUE TITLE
SteelSeries 3 Wireless Light Settings

### ISSUE THREAD

**Issue by alvarogaro** [flozz/rivalcfg#197]
Hi, I bought the SteelSeries 3 wireless mouse this Christmast. I found it a really good mouse but i have a problem. In my laptop , I only have Debian11 installed as OS. I am an university student so I go to library and for me, is really annoying having mouse lights working on the library. I really want if it's possible for you to implement light control for Steelseries rival 3 wireless . I would really apreciate it.

**Comment by flozz** [comment]
Hello,

I still have some work to do on this device but I cannot work on it currently as I do not own the device and my colleague that lend it to me is not available...

I close this issue as there is already #146 about the support of this device :)
