### ISSUE TITLE
Output format 

### ISSUE THREAD

**Issue by dvtkrlbs** [flozz/rivalcfg#198]
The default battery level output is not really machine readable. I was trying to create a gnome extension for getting the battery status and I think a json output flag or something similiar might be useful. I can try to create a PR with couple of pointers on how to do this. (I know you can still parse the output)

**Comment by flozz** [comment]
Hello,

The Rivalcfg CLI is designed for humans, but Rivalcfg provides a really simple Python API to be used by other programs.

To get the battery level for example:

```python
import rivalcfg, json
mouse = rivalcfg.get_first_mouse()
print(json.dumps(mouse.battery))
```

If you want to do the same with a "one liner" cli:

```
python3 -c "import rivalcfg,json;print(json.dumps(rivalcfg.get_first_mouse().battery))"
```

The result will be something similar to this:

```json
{"is_charging": false, "level": 50}
```

:)
