### ISSUE TITLE
Wireless Mouse Battery Level System Tray Icon

### ISSUE THREAD

**Issue by JeremiahClifford** [flozz/rivalcfg#199]
Is there any chance that Rivalcfg could have a system tray icon to display the battery level of a wireless mouse so that you could see the battery level of your mouse without having to open the terminal and input the command?

**Comment by flozz** [comment]
Rivalcfg is currently only a CLI and a Python library, so it will not implement any GUI nor tray icon (at least not as a direct part of it, it can be a separated program).

Someone seems to be working on a GNOME Shell extension to display the battery level (see https://github.com/flozz/rivalcfg/issues/198), and it should not be too difficult to implement a simple Python script that display a tray icon using TKinter

**Comment by flozz** [comment]
Hum... It seems there is nothing in tk for handling systray... But I found a way to do it with [pystray](https://pystray.readthedocs.io/en/latest/usage.html) and [Pillow](https://pillow.readthedocs.io/en/stable/):

```
pip install rivalcfg pystray pillow
```

```python
import os

os.environ["PYSTRAY_BACKEND"] = "xorg"

import threading
import time

from PIL import Image, ImageDraw
import pystray
import rivalcfg


def create_image(
    percent,
    width=16,
    height=16,
    color_bg="black",
    color_high="lime",
    color_low="red",
):
    image = Image.new("RGB", (width, height), color_bg)
    dc = ImageDraw.Draw(image)
    bar_height = max(min(int(height * percent / 100), height), 1)
    dc.rectangle(
        (0, height - bar_height, width, height),
        fill=color_high if percent > 25 else color_low,
    )
    return image


mouse = rivalcfg.get_first_mouse()

icon = pystray.Icon(
    "test name",
    icon=create_image(0),
)
threading.Thread(target=icon.run).start()

while True:
    battery_info = mouse.battery
    level = 0
    if battery_info["level"]:
        level = battery_info["level"]
    icon.icon = create_image(level)
    time.sleep(60)
```

This code can be improved but it works :)

**Comment by yurtemre7** [comment]
You guys may want to look into what I made: https://github.com/yurtemre7/mouse-battery
:)
