### ISSUE TITLE
Rival 300 CS:GO edition 1038:1394 

### ISSUE THREAD

**Issue by Meehanick** [flozz/rivalcfg#20]
Hi,
my mouse is not being detected by rivalcfg

```
$ lsusb
Bus 003 Device 006: ID 1038:1394 SteelSeries ApS 
```

```
$ rivalcfg
E: No compatible mouse found. Type 'rivalcfg --help' for more informations.
```

```
$ DEBUG_DRY=true DEBUG_MOUSE=1038:1394 rivalcfg
[DEBUG] Debugging rivalcfg 2.4.3...
[DEBUG] Python 2.7.13
[DEBUG] Dry run enabled
[DEBUG] Debugging mouse profile 1038:1394
[DEBUG] No mouse profile found
E: No compatible mouse found. Type 'rivalcfg --help' for more informations.
```

```
$ DEBUG_DRY=true DEBUG_MOUSE=1038:1394 rivalcfg -c red
[DEBUG] Debugging rivalcfg 2.4.3...
[DEBUG] Python 2.7.13
[DEBUG] Dry run enabled
[DEBUG] No mouse profile found
Usage: rivalcfg [options]

rivalcfg: error: no such option: -c
```

Any ideas/suggestions?

**Comment by flozz** [comment]
Hello,

Can you install **rivalcfg 2.4.4** (I released it just now) and then try the following command:

    DEBUG_PROFILE=1038:1710 DEBUG_DEVICE=1038:1394 rivalcfg -c red

Does it work?

**Comment by Percinnamon** [comment]
I have this model of mouse, and about 2 months ago I made my own changes to the source code which allowed me to control the mouse. This is my first time contributing to any software project, so please forgive me because I have not used github or made a commit before. I followed the protocol flozz described in a blog post about how he used wireshark and virtualbox to reverse engineer the driver. I have a working tarball which I have compiled and installed on my system which allows me to use the CSGO Fade edition of the mouse.

**Comment by flozz** [comment]
Hello,

If you can share your work (at least the instruction set of the mouse), I will be able to add its support in rivalcfg :)

**Comment by Percinnamon** [comment]
I have the complete tarball, but I am rather lost on how I am supposed to upload it. Again, I'm sorry this is my first time on here. Github won't allow me to attach a tar.gz file to this post. How would you like me to upload it?

**Comment by flozz** [comment]
Github allows to upload .zip files in issues, so you can compress your tarball as zip and then drag&drop it on the "comment" text field, it should be uploaded automatically :)

**Comment by Percinnamon** [comment]
[rivalcfg-2.4.3.1.zip](https://github.com/flozz/rivalcfg/files/853141/rivalcfg-2.4.3.1.zip)

**Comment by flozz** [comment]
Thank you, I will look at your work to integrate it in rivalcfg! :D

**Comment by flozz** [comment]
The support of this mouse was added to rivalcfg 2.5.0, thank you @Percinnamon for your help!
