### ISSUE TITLE
Regex doesn't match on hosts with > 10 USB busses

### ISSUE THREAD

**Issue by four0four** [flozz/rivalcfg#21]
Hey all,

Udev identifies my mouse as something like this:
`/devices/pci0000:00/0000:00:12.0/usb10/10-4/10-4:1.1/0003:1038:1384.001B/input/input40`

This fails to match the default regex (`^.*/usb./[0-9/.-]+:[0-9]+\.%i/[0-9]+:%s:%s.*$`) , which appears to only expect usb0 thru usb9. I'm not great at regex, but I patched mine to `^.*/usb\d+/[0-9-]+/[0-9-]+:[0-9-]+\.%i/[0-9]+:%s:%s.*$`, and that seems to work so far. There may be cleaner ways to express it, so I'll leave that up to you :)

for reference, should it matter, this is on 4.10.6-1-ARCH.

**Comment by flozz** [comment]
Thank you ! It is now fixed in **v2.5.1** :)
