### ISSUE TITLE
Can't change anything

### ISSUE THREAD

**Issue by fleekoxd** [flozz/rivalcfg#22]
Hey,
I am very new to Linux (currently using Ubuntu 16.04.2). Currently I am trying to set-up my mouse to work like it works on Windows. To my knowledge I have followed all the steps correctly and when I try to change some feature on my Rival 100 I get an error message.

`linuxuser69@LinuxPC:~$ rivalcfg --color=black
Traceback (most recent call last):
  File "/home/linuxuser69/.local/bin/rivalcfg", line 11, in <module>
    sys.exit(main())
  File "/home/linuxuser69/.local/lib/python2.7/site-packages/rivalcfg/cli.py", line 172, in main
    mouse = RivalMouse(profile)
  File "/home/linuxuser69/.local/lib/python2.7/site-packages/rivalcfg/rival_mouse.py", line 24, in __init__
    self._device_open()
  File "/home/linuxuser69/.local/lib/python2.7/site-packages/rivalcfg/rival_mouse.py", line 48, in _device_open
    self._device = open(self.device_path, "wb")
IOError: [Errno 13] Permission denied: u'/dev/hidraw2'`

I Have no idea on what I am suppose to do.
The version Of the rivalcfg i am using is:
`linuxuser69@LinuxPC:~$ rivalcfg --version
2.5.1
`

**Comment by flozz** [comment]
Hello,

It is a permission issue: udev rules have probably not been installed. To install them,

* download the following file: https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules
* put it in the `/etc/udev/rules.d` folder
* and run the following command: `udevadm trigger`

It should work better after that :)

**Comment by fleekoxd** [comment]
@flozz Going to sound like an idiot, but when i click on that link raw data comes up. Do i just copy and paste that onto a new document and put that in there?

**Comment by flozz** [comment]
Hello, you can use the following command to download the file at the right place :

    sudo wget https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules -O /etc/udev/rules.d/99-steelseries-rival.rules

And then run 

    udevadm trigger

:)

**Comment by flozz** [comment]
Hello,

I close this issue assuming you solved your problem. If not, please re-open it. :)
