### ISSUE TITLE
Aerox 3 Wireless never seems to persist my color settings (#000000 for everything. Max power savings.)

### ISSUE THREAD

**Issue by ipaqmaster** [flozz/rivalcfg#229]
#### What happened

I have to run my rivalcfg command every time to ensure the mouse doesn't engage its LEDs. I was dealing with multiple charges per day when they were left on. It's much easier to charge every second day or even later by leaving them off.

The command I currently issue at graphical session start (automatically) and manually after going from usb-c charging back to wireles mode is: `/usr/bin/rivalcfg -p 1000 -s "800,800,800,800,800" -t 3 -T 0 -a 000000 --top-color 000000 --middle-color 000000 --bottom-color 000000`

#### What was expected

Mouse should persist these "Stay dark" settings.

#### Step to reproduce

* Is the bug always reproducible or is it "random"?

→

Issue a rivalcfg command which makes the LEDs stay off. Simply turn the mouse off (2.4GHz/Off/Bluetooth switch to the centre position) then back to the 2.4GHz position and the LEDs back on like the command never happened.

### System information

```
<!-- Please provide the output of the `rivalcfg --print-debug` command here -->
RIVALCFG
========
Version: 4.11.0
udev rules installed: True
udev rules up to date: True
Installation path: /usr/lib/python3.11/site-packages/rivalcfg

OPERATING SYSTEM
================
OS: Linux
Platform: Linux-6.7.8-arch1-1-x86_64-with-glibc2.39
Version: #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000
Distribution issue: Arch Linux \r (\l)

PYTHON
======
Python version: 3.11.8
HIDAPI version: 0.14.0

PLUGGED STEELSERIES DEVICES ENDPOINTS
=====================================
1038:1838 | 00 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 00 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 01 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 02 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 03 | SteelSeries Aerox 3 Wireless (firmware v0)
1038:1838 | 04 | SteelSeries Aerox 3 Wireless (firmware v0)


```

**Comment by flozz** [comment]
Hello,

As written in the [documentation page of the device](https://flozz.github.io/rivalcfg/devices/aerox3_wireless.html):

> On newer SteelSeries mice, the color settings are not saved in the onboard memory anymore (see Default Lighting bellow).

This is not a Rivalcfg bug but a design choice of SteelSeries for their hardware.

---

To turn off lighting by default, you may use the following command instead of setting a black color:

    rivalcfg --default-lighting off

---

Additionally I am thinking of a way to restore last known settings each time the mouse is plugged to the computer, at least on Linux.

**Comment by flozz** [comment]
For reference, here is a related issue: https://github.com/flozz/rivalcfg/issues/191

**Comment by ipaqmaster** [comment]
Thanks for that command I've run it.

I too was considering something like a udev rule to run say, a one-liner bash script which just contains my rivalcfg command as mentioned. If rivalcfg could implement its own persistent settings option that would certainly be nifty - though in regular use-cases people buying new mice would probably find the flags change for their changed model anyway - invalidating their persistent settings.

**Comment by flozz** [comment]
Since v4.4.0, Rivalcfg started to save settings on disk (`~/.config/rivalcfg`). This was a mandatory step to be able to implement a GUI. Maybe in the future it will be also used to restore settings at startup / when mouse is plugged back. :)
