### ISSUE TITLE
Rival 500 Support

### ISSUE THREAD

**Issue by kant1** [flozz/rivalcfg#23]
Hi

I have the Rival 500, I can do test, map or other stuff to add the support of it.

Just give me the instruction ;)

**Comment by flozz** [comment]
Hello,

To support this mouse, its control commands must be reverse-engineered. To do so, you have to:

* Captures data from the USB bus
* Play with the official SteelSeries Engine 3 (on windows, possibly in a VM)
* then analyze what have been captured to find commands used by the SS Engine

I wrote an article about the reverse-engineering of my Rival 100 (in french):

* http://blog.flozz.fr/2016-03-27/steelseries-rival-100-reverse-engineering-peripherique-usb/

**Comment by Zyian** [comment]
I have a Rival 500 as well, I'll try to get the information you need. (Time to use my elementary french classes to the test)

I'll see if I can get going next week.

**Comment by flozz** [comment]
Hello I close this issue, please continue discussions in #32 :)
