### ISSUE TITLE
Update the package on AUR

### ISSUE THREAD

**Issue by Thiblizz** [flozz/rivalcfg#24]
Hello,

My main system is on Arch Linux, and I prefer to get my packages from AUR.
I already flagged it as outdated [rivalcfg-git](https://aur.archlinux.org/packages/rivalcfg-git).

By the way I've started to reverse engineering the SteelSeries Rival 500 (will do as well the 700 if I get enough money), I will push all the patchs as soon as I have finished.

Thanks for your project, it's really helpful.

**Comment by flozz** [comment]
Hello,

Thank you for interest in rivalcfg, if you need some help to do the reverse engineering of your mouse, don't hesitate to ask! :)

**Comment by Thiblizz** [comment]
If the acual maintainer is no more active, I would be glad to take care of it.

Let me know about it ;).

**Comment by flozz** [comment]
I do not have any contact with the Arch package maintainer, feel free to maintain he is unresponsive :)

**Comment by Thiblizz** [comment]
I will update it in a few days ;).

**Comment by flozz** [comment]
Ok, thank you
