### ISSUE TITLE
Ubuntu can't change DPI ( Rivals 300)

### ISSUE THREAD

**Issue by lordzeref** [flozz/rivalcfg#26]
Hi man

I cant change my dpi's? Im new to linux so this readme is a little bit hard for me lol, but it keep saying Permission denied: u'/dev/hidraw4'
when i tried to change '' rivalcfg --sensitivity2=1800 ''

**Comment by flozz** [comment]
hello,

It seems that the udev rules have not been installed. Execute the following commands, it should fix your problem:

```
sudo wget https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules -O /etc/udev/rules.d/99-steelseries-rival.rules
```

```
sudo udevadm trigger
```

then it should work :)

**Comment by lordzeref** [comment]
Hi. i tried it again and it said :
--2017-05-10 13:03:57--  https://raw.githubusercontent.com/flozz/rivalcfg/master/rivalcfg/data/99-steelseries-rival.rules
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.84.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.84.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 450 [text/plain]
Saving to: ‘/etc/udev/rules.d/99-steelseries-rival.rules’

/etc/udev/rules.d/9 100%[===================>]     450  --.-KB/s    in 0s      

2017-05-10 13:03:57 (116 MB/s) - ‘/etc/udev/rules.d/99-steelseries-rival.rules’ saved [450/450]


After i executed the commands, nothing shows up when i trpe the command to change sensitivity? :S

**Comment by flozz** [comment]
Hello,

No, nothing will be displayed when you type this command. The sensitivity is just changed. If you need a visual feedback that everything is working, you can try to change the color of the mouse logo:

    rivalcfg -c red

:)

**Comment by flozz** [comment]
I close this issue, please re-open it if your problem is not solved :)
