### ISSUE TITLE
SyntaxError: can't assign to operator

### ISSUE THREAD

**Issue by lollo03** [flozz/rivalcfg#30]
![image](https://cloud.githubusercontent.com/assets/23106263/26326943/c57a30f2-3f3d-11e7-9958-c9ae280c65b3.png)

**Comment by flozz** [comment]
Hello,

you typed your command in a python shell, but rivalcfg cannot be used this way, you have to type the command in you normal shell (bash, sh, zsh,...)

![capture d ecran de 2017-05-22 22-32-43](https://cloud.githubusercontent.com/assets/971438/26327240/e1ac80ee-3f3e-11e7-969b-d0a39043fa06.png)

**Comment by lollo03** [comment]
if i type in the command sehll it says me "unknow command"

**Comment by flozz** [comment]
That means you not installed rivalcfg. To install it, type the following command :

    sudo pip install rivalcfg 

It should work then

**Comment by lollo03** [comment]
Thank! i'ts now working
