### ISSUE TITLE
Can't do anything with my Rival 100. Ubutu Gnome Shell 16.04 LTS

### ISSUE THREAD

**Issue by hydargos123** [flozz/rivalcfg#34]
Hello,

I am running Ubuntu Gnome Shell 16.04 LTS on a HP ENVY 15-ae112nf laptop.
I have installed RivalCFG version 2.6.0. I am using a Rival 100 mice, and its working perfectly on Windows 10 on the same computer.
The mice also work nice on Ubuntu, except the colors that i cant change (obviously).

But when i run RivalCFG, i got this:
http://i.imgur.com/QbAVDEf.png
```
hydargos123@Vydar:~$ rivalcfg -c red
Traceback (most recent call last):
  File "/home/hydargos123/.local/bin/rivalcfg", line 11, in <module>
    sys.exit(main())
  File "/home/hydargos123/.local/lib/python2.7/site-packages/rivalcfg/cli.py", line 172, in main
    mouse = RivalMouse(profile)
  File "/home/hydargos123/.local/lib/python2.7/site-packages/rivalcfg/rival_mouse.py", line 24, in __init__
    self._device_open()
  File "/home/hydargos123/.local/lib/python2.7/site-packages/rivalcfg/rival_mouse.py", line 48, in _device_open
    self._device = open(self.device_path, "wb")
IOError: [Errno 13] Permission denied: u'/dev/hidraw0'

hydargos123@Vydar:~$ sudo rivalcfg -c red
[sudo] password for hydargos123 : 
sudo: unknown command: rivalcfg 

hydargos123@Vydar:~$ rivalcfg -l
SteelSeries Rival                             1038:1384   
SteelSeries Rival 100                         1038:1702   (plugged)
SteelSeries Rival 300                         1038:1710   
SteelSeries Rival 300 CS:GO Fade Edition      1038:1394   
SteelSeries Rival 300 CS:GO Hyperbeast Edition 1038:171a   
hydargos123@Vydar:~$ rivalcfg --version
2.6.0

hydargos123@Vydar:~$ 
```
When i try to change the color, it display some errors messages. When i try to run it with sudo, it say that the command doesnt exist. But RivalCFG detect the mouse as plugged...
Did i make something wrong ? can you help me ?

Sorry for my weird English, and thank you.
hydargos123

**Comment by flozz** [comment]
Hello,

You have this error because the udev rules are not installed. See this to solve your problem:

* https://github.com/flozz/rivalcfg#i-have-a-permission-denied-error-what-can-i-do

:)

**Comment by hydargos123** [comment]
Hello,

Sorry, i didn't read the FAQ ^^

It's working perfectly now.

Thank you!
