### ISSUE TITLE
Arch package fails to install

### ISSUE THREAD

**Issue by lemonsrc** [flozz/rivalcfg#35]
Cannot install `rivalcfg-git` from the AUR. Fails with the following error:
```
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```
Installing `rivalcfg-git` works successfully after installing the `python-pip` Arch package. Seems like a missing dependency?

**Comment by flozz** [comment]
Hello,

`setuptools` is actually required to make `setup.py` working, but I cannot add it to dependency of my python package as the dependencies are listed in the `setup.py` file that cannot be used if `setuptools` is not installed...

We should ask the maintainer of the Arch package to add this dependencies to the `PKGBUILD` file (`makedepends=('git' 'python-setuptools')`)  (cc @defkeh, @Thiblizz).

Currently you can workaround by installing the `python-setuptools` package manually :)

**Comment by Thiblizz** [comment]
So sad, someone took the ownership of the package just after I asked to maintain it :(.

**Comment by flozz** [comment]
I commented on AUR to tell the maintainer to update :)

**Comment by yorickr** [comment]
Hey, current maintainer here. I updated the package accordingly.

I took ownership a while ago for some reason I can't remember, probably wanted to update it a bit. 

@Thiblizz if you'd like ownership just tell me. Could also add you as a co-maintainer if you'd like, just tell me your AUR username.

**Comment by lemonsrc** [comment]
AUR package was updated to include `python-setuptools` as a dependency and is now working as intended
