### ISSUE TITLE
rivalcfg 3.0.0

### ISSUE THREAD

**Issue by flozz** [flozz/rivalcfg#42]
I am currently working on rivalcfg 3.0.0. This version was previously developed on the `road-to-3-0-0-hidapi` branch but it is now mered on `master`. This version is not yet ready but putting it on `master` will make it easier for contributer to work on and for everyone to test it :).

In addition to internal architecture change, rivalcfg is now relying on the `hidapi` third party library instead of `pyudev` (packagers will have to update their package).

If you have any question about this version, feel free to ask it here or to open an issue ;)

**Comment by frags51** [comment]
Please update the documentation (Readme.md) to reflect Heroes of the Storm addition too.

**Comment by flozz** [comment]
@frags51 It is already in my TODO list, I will do it this evening :D

**Comment by yorickr** [comment]
[Arch](https://aur.archlinux.org/packages/rivalcfg-git) maintainer here, it should work on Arch now with the new dependencies. I'd appreciate someone confirming if it works on their machine though, thanks.

**Comment by flozz** [comment]
@yorickr Hello, I installed an Archlinux VM and installed the package: It works! Thank you! :)

**Comment by sungod23** [comment]
What can I do to help add the Fallout4 rival300 to this utility?

**Comment by flozz** [comment]
@sungod23 This mouse probably use the same instruction set that the regular Rival 300. To be able to support it, I will first need some informations about the mouse:

1. Is it this one? → https://www.amazon.com/dp/B01ENQWDAG/
2. I will need the product ID of the mouse. On linux you can get it with the following command:

    lsusb | grep 1038

:)

**Comment by sungod23** [comment]
I think so, it appears to be. I got mine from betshot:
https://store.bethsoft.com/accessories/gaming-accessories/vault-111-steelseries-rival-mouse
I tried adding it into the version of the repo under rivacfg/mice, copied the plain rival300 .py and edited, then added it to __init__.py but there are obviously some other places it wants to be. Product ID is 1712, so just off the base rival. Usb device output below. I actually have the pip version installed. 
Thanks so much!

sudo usb-devices | grep 1038 -B2 -C7
T:  Bus=02 Lev=02 Prnt=02 Port=01 Cnt=01 Dev#=  4 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=1038 ProdID=1712 Rev=00.25
S:  Manufacturer=SteelSeries
S:  Product=SteelSeries Rival 300 Fallout 4 Gaming Mouse
C:  #Ifs= 4 Cfg#= 1 Atr=a0 MxPwr=200mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
I:  If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=02 Driver=usbhid
I:  If#= 2 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=01 Prot=01 Driver=usbhid
I:  If#= 3 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid

**Comment by flozz** [comment]
Can you try (with the latest revision on master) the following command:

    RIVALCFG_PROFILE=1038:1710 RIVALCFG_DEVICE=1038:1712  rivalcfg -c red

**Comment by yorickr** [comment]
Maybe open a new issue for this next time @sungod23 ?

**Comment by flozz** [comment]
@yorickr you are right, I opened a new issue → #44 

@sungod23 please answer in the issue #44  :)

**Comment by flozz** [comment]
As this version take time to be released, I released a beta version: `v3.0.0-beta1` that can be installed from PYPI :)

**Comment by flozz** [comment]
I close this issue as rivalcfg 3.0.0 is released. It can now be installed with the following command as root:

    pip install rivalcfg
