### ISSUE TITLE
Can't get this tool to run

### ISSUE THREAD

**Issue by kamild1996** [flozz/rivalcfg#45]
When I try to "pip install rivalcfg", it outputs: https://gist.github.com/kamild1996/18d64cd7dd173ad137af77fcdeed9473

but I still cannot run the tool using the 'rivalcfg' command, it just says it doesn't exist.

Compiling also fails with the following error: https://gist.github.com/kamild1996/6295d874c9b48f5f65b66fe4fecf16fc

**Comment by flozz** [comment]
Hi,

To install rivalcfg system-wild, you have to run the command as root:

    sudo pip install rivalcfg

To build it from source (to use the latest development version), you need to have the header files of libusb on you system, this can be installed with the following command on Debian / Ubuntu:

    sudo apt install libusb-dev

**Comment by kamild1996** [comment]
Installing it as sudo helped, thanks!

I'm trying to set the polling rate with this tool (sudo rivalcfg --polling-rate=1000). When I do these commands, I get no other output. Is there any way to tell the setting was changed successfully? Because I can't quite feel the difference between 125Hz and 1000Hz.

**Comment by flozz** [comment]
There is no feedback when the command is successful. 

You can calculate the poling rate from the poling interval. The is an article on the Archlinux Wiki about that:

* https://wiki.archlinux.org/index.php/Mouse_polling_rate#Display_polling_interval

**Comment by kamild1996** [comment]
The first method with 'grep -B3 -A6 1038.*1702 /sys/kernel/debug/usb/devices' doesn't work because I don't have such a directory, but 'lsusb -vd 1038:1702 | grep bInterval' showed me 'bInterval 1'. Looks like the note on the wiki page is right, it might not show the actual interval being used because the same value was being reported after changing to different rates with rivalcfg.

But I managed to run [this app](https://eu.cybergamer.com/files/2260/) under Wine (requires 'mfc42' to run) and it did register the changes, so I'll take it as "it works". Thank you for the tool again :)
