### ISSUE TITLE
Rival 600 support

### ISSUE THREAD

**Issue by AntouanK** [flozz/rivalcfg#47]
Thanks for your work.

Would this work for Rival 600? `1038:1724`
( https://steelseries.com/gaming-mice/rival-600 )

**Comment by flozz** [comment]
Hello,

This mouse is currently not supported by rivalcfg. Maybe it will be supported one day, if someone do some reverse engineering on it :)

**Comment by AntouanK** [comment]
Is there anyway I can help with that?

I was able to use `xinput` to tweak sensitivity etc, but it would be nice to tweak the RGB stuff as well. :)
In any case, thank you.

**Comment by flozz** [comment]
You can help by helping to do the reverse engineering of the mouse. To do so, you need to capture what the SteelSeries Engine send to the mouse for each setting. I wrote an article on this if you a re interested :)

**Comment by FFY00** [comment]
@AntouanK that's all software based, obviously not optimal.

**Comment by AntouanK** [comment]
@flozz link to the article?

**Comment by AntouanK** [comment]
@FFY00 Is there any other way?

**Comment by FFY00** [comment]
@AntouanK yes, the mouse keeps the settings so you can program it on windows (works in a virtual box). This is also not optimal because you would need to boot windows or start a virtual machine every time you want change your mouse settings. If you work with @flozz you can add support dor the mouse in this project which would be the optimal solution.

**Comment by AntouanK** [comment]
@FFY00 
I was thinking about that.
So you pass the usb device to the vm, and set it up there. right?

**Comment by flozz** [comment]
Hi,

The article is here: https://blog.flozz.fr/2016/03/27/steelseries-rival-100-reverse-engineering-dun-peripherique-usb/

It is in French, but Google translate should help: https://translate.googleusercontent.com/translate_c?depth=1&nv=1&rurl=translate.google.fr&sl=fr&sp=nmt4&tl=en&u=https://blog.flozz.fr/2016/03/27/steelseries-rival-100-reverse-engineering-dun-peripherique-usb/&xid=17259,15700019,15700105,15700122,15700124,15700149,15700168,15700173,15700201&usg=ALkJrhhgQCeEEMnqVC3BpfIGH6YJnreSwQ

**Comment by AntouanK** [comment]
@FFY00 I tried to use a Windows VM on virtualbox, and unfortunately, as soon as I pass the USB device to windows, the "cursor" of the mouse is stuck.
The mouse itself moves (I can see stuff highlighted as I hover the mouse) but the pointer of the mouse is not. So it's practically impossible to use it.
I did manage to install the app and launch it, but it asks for a firmware update, and when I try to update it, it gets stuck and the mouse has a blue light blinking.
 :/

**Comment by flozz** [comment]
@AntouanK when you connect the mouse to the VM, it is no more available on your Linux host. And if you do not see the pointer, it is because VirtualBox hide it inside the VM (because it is normally already visible outside the VM).

To avoid having trouble, connect a second mouse to the PC. That way, you will be able to use it when your Rival is connected to the VM.

**Comment by FFY00** [comment]
Exactly! As @flozz said, you need to plug another mouse into the computer.

**Comment by AntouanK** [comment]
I think I was misunderstood.
I get that it's connected to the VM.
The linux host sees nothing, fine.
But *inside* the VM is the problem.
The "pointer" ( that white arrow ) doesn't seem to move, but I can see that I can click things.
Does that make sense?

**Comment by AntouanK** [comment]
I know it's difficult to explain. I cannot even google it.
here : https://photos.app.goo.gl/tBiE8v91XL62evqW2
hopefully it explains it better.
( also, after that, I cannot go back to the virtualbox menus. Only way is to shutdown the vm via the keyboard )

**Comment by AntouanK** [comment]
Connected the second mouse, so I can control things with that.
I guess the only problem is that if I want to tweak sensitivity and speed, I still cannot move the pointer with the rival mouse.

Btw, is this normal? ( firmware update is stuck there, nothing happens, just the logo on the mouse blinking blue )
![screenshot_2018-03-12_10-39-27](https://user-images.githubusercontent.com/4569111/37279134-cb8cd086-25e1-11e8-98cd-9d22155c9291.png)

**Comment by AntouanK** [comment]
tip: if you go `Input -> Mouse integration` on virtualbox, and untick it, you can see the VMs pointer ;)

**Comment by AntouanK** [comment]
What I've noticed now is that the speed and acceleration/deceleration is very different in the windows VM and the linux host.
I did unset the xinput property, but still it's way too more sensitive in linux.
Is there anything else to disable or reset?

**Comment by FFY00** [comment]
Hum... that's a weird behavior. Yes, the sensitivity is much higher on linux, you should set it to max in Windows.

**Comment by ergor** [comment]
I'm working on support for the Rival600 atm. I got sensitivity working, and hopefully colors soon. The 600 sends insanely large data frames for colors (>600 bytes), because it uses the same command for solid color and all the effects for the 8 different LEDs. Probably gonna need to use "value_transform" for rgbcolor on this one and maybe some subclasses of the 600 for all the effect options and configurations.

Will try to post my findings on my website and link to it asap if anybody wants to chime in

**Comment by ergor** [comment]
I have submitted a PR with support for Rival 600 (pr #60). It adds support for sensitivity, polling rate and 3 color modes: steady, shifting, trigger.

For the impatient, it can be [cloned form here](https://github.com/ergor/rivalcfg)

**Comment by sdfgeoff** [comment]
Just tested with my Rival 600 and setting the colors is working great. Thanks.

**Comment by flozz** [comment]
Thanks for the feedback :)

I will release a new rivalcfg version with the Rival 600 support on PyPI soon, and I will close this issue once done.

**Comment by parker789** [comment]
I'm getting an error when trying to run rivalcfg with my Rival 600. `The following mouse was found but rivalcfg was not able to open it:` any clue as to what this could be?

**Comment by parker789** [comment]
I rebooted and things went away for me as well. Good call :) all is well on my end

**Comment by flozz** [comment]
I released **rivalcfg 3.0.0** just now with the Rival 600 support. Thanks you all for your help to support this mouse :)

**Comment by AntouanK** [comment]
Thanks for your work.

This is a bit strange.
I get the `rivalcfg-3.0.0.beta1-1` package from AUR ( https://aur.archlinux.org/packages/rivalcfg/ ) but it installs `2.6.0`

```
$ rivalcfg --version && rivalcfg -l
2.6.0
SteelSeries Rival                                  1038:1384
SteelSeries Rival 100                              1038:1702
SteelSeries Rival 110                              1038:1729
SteelSeries Rival 300                              1038:1710
SteelSeries Rival 300 CS:GO Fade Edition           1038:1394
SteelSeries Rival 300 CS:GO Hyperbeast Edition     1038:171A
SteelSeries Rival 310 (Experimental)               1038:1720
SteelSeries Rival 500 (Experimental)               1038:170E
SteelSeries Heroes of the Storm (Sensei Raw)       1038:1390
```

**Comment by flozz** [comment]
Hello,

The version written in the beta package is wrong. Anyway it is outdated, the latest version is the 3.0.0. Maybe you should tell the package maintainer to update it :)
