### ISSUE TITLE
RIval 500 Not Working

### ISSUE THREAD

**Issue by Threat-Hunter** [flozz/rivalcfg#49]
Whenever I try to run rivalcfg I get the following error:
```
> ~ $ rivalcfg -c aqua
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 500 (Experimental) (1038:170E)
  * error: open failed

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

Usage: rivalcfg [options]

rivalcfg: error: no such option: -c
```

**Comment by flozz** [comment]
hello,

which version of rivalcfg are you using? You installed it from pypi or from this repository?

:)

**Comment by Threat-Hunter** [comment]
From the repository

**Comment by Threat-Hunter** [comment]
Got it working.
Re-built from source and it started working. I have to use sudo to get it to work, just fyi.

**Comment by flozz** [comment]
Hi,

sorry for the tame I took to answer this issue... Anyway, for the permission issue (using sudo), this can be caused by a missing configuration file. See this: https://github.com/flozz/rivalcfg#i-have-a-permission-denied-error-what-can-i-do

:)

**Comment by Threat-Hunter** [comment]
Thanks and no worries! I'm just glad you have this repo and you actually actively maintain it. Kudos to you flozz!
