### ISSUE TITLE
Didn't work anymore in Linux after the latest firmware update in Windows

### ISSUE THREAD

**Issue by haoanw** [flozz/rivalcfg#5]
Thanks for your contribution to this device. Today i update the latest firmware of rival 300 in windows OS with the official kit. Then I can't use this in linux anymore. All settings in linux seem to be as default and the rivalcfg can detect the device but not able to change the parameters, also no error occurred after giving the commands.

**Comment by flozz** [comment]
Maybe SteelSeries changed something in the protocol used to communicate with the mouse. But I cannot check what changed, because I only have a Rival 100, not the Rival 300 :(

**Comment by haoanw** [comment]
Thanks for your reply. I downgrade it to the previous version and it's working again. Anyway, the new upgrade has some other problems as well, i suggest not doing that at this moment :)

**Comment by vehka** [comment]
Any guesses on if I get a Rival 100 from the store, if it still works? Or should I make sure it uses an older firmware? Or is this issue limited to the Rival 300?

**Comment by flozz** [comment]
I have no idea if there is a new firmware for new Rival 100. The only thing you can do is to try :s (it still be possible to do some reverse engineering if they changed something)

**Comment by vehka** [comment]
Cool, I'll report back. =)

**Comment by sagcan** [comment]
@haoanw How can you downgrade the firmware? Having the same issue right now.

**Comment by haoanw** [comment]
@sagcan follow the instruction of resetting the mouse, (holding some buttons while plugging the cable), then install the previous version of steelseries driver, then it's done

**Comment by wilenius** [comment]
Btw the mouse I got in August worked fine, no need to downgrade the firmware. So new Rival 100 mouses seem to work.

**Comment by brianhks** [comment]
Just came home with the Mouse profile found: SteelSeries Rival 300 and it appears not to work.  Anything I can do to help debug?

**Comment by flozz** [comment]
Hello,

The only thing to do is to reverse-engineer the mouse again to see what changed. I will try to find some time to do this on the Rival 100, but I do not own a 300

**Comment by brianhks** [comment]
How do you go about doing that?  What tools do you use?

**Comment by flozz** [comment]
I wrote an article about that but it is in french: 

http://blog.flozz.fr/2016-03-27/steelseries-rival-100-reverse-engineering-peripherique-usb/

maybe google translate can help :)

**Comment by brianhks** [comment]
Nice! I'll give it a shot with my 300

**Comment by flozz** [comment]
It seems there is no new firmware for the Rival 100 (or I did not find how to install it), so I will have to find a Rival 300 if I want to see what changed

**Comment by flozz** [comment]
Hello, [I found a fix](https://github.com/flozz/rivalcfg/issues/25#issuecomment-302195070) to this issue. I will release it soon! :)

**Comment by flozz** [comment]
I just released **rivalcfg 2.5.2** and it should work now. I close this issue, please comment in #25 if it does not work for you :)

**Comment by nicob89** [comment]
Can't update it for some reason. After "pip install ." this comes up in Terminal:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-9tQByu-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-YvvxDs-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-9tQByu-build/

**Comment by nicob89** [comment]
No error at installing at all. It was my mistake. Thanks for the 2.5.2 release!
