### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by beebop217** [flozz/rivalcfg#50]
So I've done all the prerequisites, but when I go to install via pip I get this error:
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Orkqqw/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qyFCCh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Orkqqw/hidapi/`
This is literally my first day on linux, so please excuse any newbie mistakes.

**Comment by flozz** [comment]
Hello,

* Have you installed rivalcfg
  * from this repository (`git clone ...`)
  * or from PyPI (`pip install rivalcfg`)?

* What is your Linux distribution?

**Comment by beebop217** [comment]
I tried both ways. Just tried installing again and it worked for some reason, not sure what changed.
