### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Vladloga** [flozz/rivalcfg#54]
I recently bought a Rival 110 and wanted linux software for it. I am currently running Linux Mint Cinnamon 18.3 64-bit and tried installing the software from sources. The clone into the directory works fine but when i run `sudo pip install .` i get an error. I also tried `sudo pip install rivalcfg`, and this works fine but the version is 2.6.0, which does not support the Rival 110. I've seen another issue with the same error but the creator of that issue said that he doesn't know what changed and it suddently works. The error message i get is: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-EdhGDR/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gjBPol/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-EdhGDR/hidapi/ .Thanks in advance :)

**Comment by Vladloga** [comment]
Worked by installing python-dev, libusb-1.0-0-dev and libudev-dev. Thank you :)

**Comment by flozz** [comment]
I added the missing dependencies to the README :)
