### ISSUE TITLE
About installing the latest version

### ISSUE THREAD

**Issue by yilmzfurkan** [flozz/rivalcfg#56]
Hello everyone, thanks who has contributed to this awesome project. 
My issue is I got a Rival 110 mice and installed as its described on the README.md but I got the version 2.6.0 which isn't supported. Searched the old issues first but I was not be able to install the latest beta tried both from pip and from source no luck. Here is what my Terminal says:
```
The directory '/home/salty/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/salty/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/salty/Desktop/rivalcfg
  Requirement already satisfied (use --upgrade to upgrade): rivalcfg==3.0.0b1 from file:///home/salty/Desktop/rivalcfg in /home/salty/.local/lib/python2.7/site-packages
Requirement already satisfied: hidapi>=0.7.99.post20 in /home/salty/.local/lib/python2.7/site-packages (from rivalcfg==3.0.0b1)
Requirement already satisfied: setuptools>=19.0 in /home/salty/.local/lib/python2.7/site-packages (from hidapi>=0.7.99.post20->rivalcfg==3.0.0b1)
```

Thanks in advance.
OS: Xubuntu 18.04

**Comment by flozz** [comment]
Hello,

maybe you can try this:

```
pip uninstall rivalcfg
sudo pip uninstall rivalcfg
sudo  pip install rivalcfg==3.0.0b1 
```

**Comment by yilmzfurkan** [comment]
No luck it still installs version 2.6.0 however when I uninstall its says "Successfully uninstalled rivalcfg-3.0.0b1" is the -version flag bugged? When I try "rivalcfg --version" I get this
`W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 110 (1038:1729)
  * error: open failed

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

2.6.0
`

**Comment by FFY00** [comment]
Try running it with `sudo`.

**Comment by flozz** [comment]
I close this issue as rivalcfg 3.0.0 is released. It can now be installed with the following command as root:

    pip install rivalcfg

**Comment by yilmzfurkan** [comment]
@flozz thanks I was a bit lazy to provide more support since I was happy with the default settings. Everything is working now. Thank you again for this awesome project!
