### ISSUE TITLE
Rival 500 CLI: what does Reset do?

### ISSUE THREAD

**Issue by omgitsgela** [flozz/rivalcfg#57]
I have a Rival 500 mouse which seems to have locked up and won't accept CPI sensitivity configuration from the SteelSeries Engine software. Whatever it's set to, that's it, it won't take anything different. It does take configuration for polling rate and angular snapping just fine, though. I was looking for a tool that could flag the mouse to do an internal factory reset, if such an option was possible, and I came across the rivalcfg tool. Reading through the information provided, it's not clear to me exactly what the reset command does within the CLI. Does it reset to default the entire mouse, including configurations not supported by rivalcfg, or does it reset only the parameters that are configurable at this time from the configuration tool?

I ask this first because there's a lot of setup required to get rivalcfg working on Windows 10, the C++ link doesn't work, and the only tool I found was a 6GB C++ developer package, which seems excessive considering I'm not sure if this utility will help me at all yet.

**Comment by flozz** [comment]
Hello,

the `--reset` option just set all the configurations supported by rivacfg for that mouse to their known default values. I Think it wont help you that much :(

I Know the Rival 300 firmware can be upgraded with a tool, maybe this can be done for the Rival 500 too (this will probably reset the configuration too)

Regards,

**Comment by FFY00** [comment]
Try following the instructions here https://github.com/FFY00/rival310-re#force-firmware-update-reset.
It should allow you to update your firmware.

**Comment by flozz** [comment]
Hello, I close this issue as there is no more activity on it. Please re-open it if you have new questions.
