### ISSUE TITLE
sudo needed to run rivalcfg 3.0.0 with SteelSeries Rival 110 (1038:1729)

### ISSUE THREAD

**Issue by Skillzore** [flozz/rivalcfg#63]
I am just wondering. I get this message when connected through a dock:
```
rivalcfg --version 
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 110 (1038:1729)
  * error: open failed

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

3.0.0
```

Would be nice to be able to style my mouse at the office without having to plug it directly into my laptop which I disconnect/connect a lot.

**Comment by flozz** [comment]
Hello,

There should be no issues with docks or hubs (I use a dock with my Thinkpad too).

I you just installed rivalcfg, try to reboot, it seems that helps → https://github.com/flozz/rivalcfg/issues/47#issuecomment-417881594

:)

**Comment by flozz** [comment]
That'st stange :(

* Can you try to run the command as root to check it is not a permission issue?
* Is the mouse controlled by an other software (connected to a VM, usbmodswitch, ratsbag or anything else)?
* What is you distribution (and its version) to allow me to try to reproduce the bug?

**Comment by Skillzore** [comment]
I am on Ubuntu 18.04 and I have no other software controlling my mouse, that I know of. 

It works if I run it with sudo or as root. I can live with having to use sudo, but just wanted to let you know if it might be a bug.

**Comment by flozz** [comment]
Ok, if it is only a permission error, see this: https://github.com/flozz/rivalcfg#i-have-a-permission-denied-error-what-can-i-do

it should solve your issue, and allow you tu run the command as an unprivileged used :)

**Comment by Skillzore** [comment]
Yeah, that was it. Sorry and thanks for the help!
