### ISSUE TITLE
Rival 300 CS:GO Fade Edition not being detected

### ISSUE THREAD

**Issue by Creytasious** [flozz/rivalcfg#70]
I followed the installation instructions and I am unable to have the mouse be detected. I have used this software before so I'm certain I have set it up correctly. 

I run RIVALCFG_DEBUG=1  rivalcfg --list 
and it spits out 

[DEBUG] Rivalcfg 3.2.0
[DEBUG] Python version: 2.7.15rc1
[DEBUG] OS: Linux
[DEBUG] Linux distribution: Ubuntu 18.04 bionic
[DEBUG] Selected mouse: None
SteelSeries Rival                                  1038:1384   
SteelSeries Rival 100                              1038:1702   
SteelSeries Rival 110                              1038:1729   
SteelSeries Rival 300                              1038:1710   
SteelSeries Rival 300 CS:GO Fade Edition           1038:1394   
SteelSeries Rival 300 CS:GO Hyperbeast Edition     1038:171A   
SteelSeries Rival 300 Dota 2 Edition               1038:1392   
SteelSeries Rival 300 HP Omen Edition              1038:1718   
SteelSeries Rival 310 (Experimental)               1038:1720   
SteelSeries Rival 500 (Experimental)               1038:170E   
SteelSeries Rival 600 (Experimental)               1038:1724   
SteelSeries Heroes of the Storm (Sensei Raw)       1038:1390   

Initially when I installed it I tried to reset the colours with -r but it said 

rivalcfg: error: no such option: -r

I also after installing tried different USB ports, rebooting etc.

**Comment by flozz** [comment]
Hello,

Can you check that Linux detect the mouse? You can do this with the following command:

    lsusb

**Comment by Creytasious** [comment]
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 046d:c339 Logitech, Inc. 
Bus 001 Device 005: ID 046d:0825 Logitech, Inc. Webcam C270
Bus 001 Device 002: ID 1038:1716 SteelSeries ApS 
Bus 001 Device 004: ID 8087:0a2a Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

This is what that command dumps into terminal

**Comment by flozz** [comment]
Hello,

It seems your mouse product id is `1716` whereas the product id of the Rival 300 CS:GO Fade Edition  is `1394`. 

They probably released an updated version of the mouse....

* Have you a link of the product on an online store?
* can you retry your previous command as root (as the mouse is not known by rivalcfg, udev rules are not applied and so you have permission issue)

**Comment by Creytasious** [comment]
Ran again with root

sudo  RIVALCFG_PROFILE=1038:1710 RIVALCFG_DEVICE=1038:1394 rivalcfg -c ff1800
[sudo] password for corey: 
[DEBUG] Rivalcfg 3.2.0
[DEBUG] Python version: 2.7.15rc1
[DEBUG] OS: Linux
[DEBUG] Linux distribution: Ubuntu 18.04 bionic
[DEBUG] Forced profile: 1038:1710
[DEBUG] Targeted device: 1038:1394
W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Rival 300 (1038:1710)
  * error: Unable to find the requested device: 1038:1710:00

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

[DEBUG] Selected mouse: None
Usage: rivalcfg [options]

rivalcfg: error: no such option: -c

And i'm unable to provide a link for this specific mouse because I bought it in-store.

**Comment by Creytasious** [comment]
![csgofademouse](https://user-images.githubusercontent.com/19200735/46510649-b22c6d00-c88d-11e8-9304-73364b0eb42e.jpg)

**Comment by Alocks** [comment]
Same issue, same mouse, same hwd id

**Comment by flozz** [comment]
It seems there were two versions of this device, but it shoul be supported now: https://github.com/flozz/rivalcfg/blob/master/rivalcfg/profiles/rival300csgofadeeditionstm32.py

I close this issue, but tel me if does not work :)
