### ISSUE TITLE
Won't write to firmware?

### ISSUE THREAD

**Issue by archaeojsc** [flozz/rivalcfg#71]
I have a Steelseries Rival 100 on a machine running Ubuntu 18.04. The controls seem to work fine, but settings don't persist through rebooting the machine... do I need to re-enter rivalcfg every time I boot up, or am I missing something?

**Comment by archaeojsc** [comment]
Sorry, I didn't see any save option listed. So, I would enter (for example) `rivalcfg -p 250 -S1000 --save`?

**Comment by flozz** [comment]
Hi, there is no `--save` option, normally, when using CLI, rivalcfg should save config in the mouse (it send the save command to the mouse)...

If you have your mouse reset each time, there is two possibilities:

1. The memory of the mouse is defective, so it does not work,
2. You plugged the mouse on a Windows (or Mac?) computer that have the SteelSeries Engine 3 installed that automatically apply its last configuration

**Comment by archaeojsc** [comment]
Ah, I see. It's a dual-boot setup, so the windows config must be overriding the settings any time the other OS boots. Probably why my previous attempts to change the mouse polling rate under unbuntu failed as well. Thank you for clearing that up.

Ok, user error on my end then... I'll figure something out.

**Comment by flozz** [comment]
I'm happy that's not a bug in rivalcfg, good luck with your dualboot :)

**Comment by FFY00** [comment]
My bad, I thought a save function was implemented as it was a different command in the protocol. I can confirm SteelSeries Engine overwrites the settings when it launches.

**Comment by archaeojsc** [comment]
Double checked, and it does _only_ reset after booting back into the other OS and back to linux. Not an issue with `rivalcfg` at all. 

Thanks for the great little utility and for helping me figure that out!
