### ISSUE TITLE
Rival 310 Led problem  

### ISSUE THREAD

**Issue by Alexiwnl** [flozz/rivalcfg#73]
I just got a rival 310 and im not very experienced, i changed the led in the engine to multi color breath i selected the one with red and yellow and now the mouse has only white led and if i try to change it back doesent do anything.

**Comment by FFY00** [comment]
Hum something similar has happened to be before. Can you check if when you change the other led both the changes are applied to both leds?

**Comment by Alexiwnl** [comment]
I fixed it i needed to close the engine all the way not just pressing the X button .

**Comment by Alexiwnl** [comment]
I fixed it i needed to close the engine all the way not just pressing the X button .

**Comment by FFY00** [comment]
Hum, that's interesting. I might dive into that when I get time.
