### ISSUE TITLE
Rival 100 Dota Edition

### ISSUE THREAD

**Issue by osmancoskun** [flozz/rivalcfg#75]
I have dota edition rival 100 mouse and rivalcfg cant detect my mouse.
Manjaro - 4.19.14-1

```
[osman@cerberus ~]$ lsusb
Bus 006 Device 005: ID 1038:170c SteelSeries ApS 

```

```
[osman@cerberus ~]$ rivalcfg set_color blue
Error: no compatible mouse found.
```

changed udev id product
```
[osman@cerberus ~]$ sudo nano  /etc/udev/rules.d/99-steelseries-rival.rules 
# SteelSeries Rival 100
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="170c", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="170c", MODE="0666"

```
nothing has changed
also tried something you said at other issues 
```
[osman@cerberus ~]$ DEBUG_DRY=true DEBUG_MOUSE=1038:170c rivalcfg set_color green
Error: no compatible mouse found.

```

**Comment by flozz** [comment]
Hello,

Your mouse is not supported yet by rivalcfg, but if it is a standard rival 100 it will be eas to support :)

Can you confirm that it is this mouse → https://www.ldlc.com/fiche/PB00217133.html ?

**Comment by osmancoskun** [comment]
yes sir. this is definitely my mouse. normal rival 100 working fine with rivalcfg but this one doesnt :) thanks for support aswell

**Comment by flozz** [comment]
Hello,

I implemented support for you mouse in  a branch, can you test it and tell me if it work?

```
# 1. Clone this repository
git clone https://github.com/flozz/rivalcfg.git
# 2. Go to the cloned repository
cd rivalcfg
# 3. Checkout the test branch
git checkout rival100dota2edition
git pull
# 4. Test if it work
sudo python -m rivalcfg -c green
sudo python -m rivalcfg -c blue 
```

:)

**Comment by osmancoskun** [comment]
i was away from my computer. sorry for that. 
it works like a charm :) its so nice to see that my mouse no need windows anymore for steelseries engine
thanks for your support.

**Comment by flozz** [comment]
Thank you for the feedback :)

→  **rivalcfg 3.5.0** released with the Rival 100 Dota 2 Edition support.
