### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by angiioh** [flozz/rivalcfg#78]
Hi! I followed the instructions to install via pip, but I am encountering an error:
The directory '/home/angii/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/angii/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting rivalcfg
  Downloading https://files.pythonhosted.org/packages/df/d8/1f5ba004d12d2589e24858b7641af4151830b86c5f5b16279fd04cb0a7be/rivalcfg-3.6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-soTDQ5/rivalcfg/

Any ideas? Sorry if I'm missing something obvious.

**Comment by flozz** [comment]
Hello,

try to install setuptools first.

On Ubuntu / Debian:

    sudo apt install python-setuptools

else you can use pip:

    sudo pip install setuptools

:)

**Comment by angiioh** [comment]
Thank you! I appreciate your help. That seemed to move things along but I'm still getting some errors: 
Collecting rivalcfg
  Using cached https://files.pythonhosted.org/packages/df/d8/1f5ba004d12d2589e24858b7641af4151830b86c5f5b16279fd04cb0a7be/rivalcfg-3.6.0.tar.gz
Collecting hidapi>=0.7.99.post20 (from rivalcfg)
  Using cached https://files.pythonhosted.org/packages/c1/86/89df0e8890f96eeb5fb68d4ccb14cb38e2c2d2cfd7601ba972206acd9015/hidapi-0.7.99.post21.tar.gz
Collecting setuptools>=19.0 (from hidapi>=0.7.99.post20->rivalcfg)
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
Building wheels for collected packages: rivalcfg, hidapi
  Running setup.py bdist_wheel for rivalcfg ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4Dort4/rivalcfg/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpRvdih7pip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for rivalcfg
  Running setup.py clean for rivalcfg
  Running setup.py bdist_wheel for hidapi ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4Dort4/hidapi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpcDkZVgpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for hidapi
  Running setup.py clean for hidapi
Failed to build rivalcfg hidapi
Installing collected packages: setuptools, hidapi, rivalcfg
  Running setup.py install for hidapi ... done
  Running setup.py install for rivalcfg ... done
Successfully installed hidapi-0.7.99.post21 rivalcfg-3.6.0 setuptools-41.0.1

**Comment by flozz** [comment]
Oops, I forget about this issue... I close it but please reopen it if it is not solved... sorry :(
