### ISSUE TITLE
Rival 110 :: Is possible to config left buttons and RGB?

### ISSUE THREAD

**Issue by Emilisdls** [flozz/rivalcfg#80]
Hello, I tried out this rep on POP_os! for the 110 and seems to work like a charm but I need to custom config the buttons on the left of the mouse and the documentation doesn't seem to have the feature. Any idea?

Also, this is not that important but had someone got an RGB profile or multiples colors working?

**Comment by Emilisdls** [comment]
Left buttons are buttons 4 and 5 according to windows app.

**Comment by flozz** [comment]
Hello,

For the colorshift, I answered in #85. For the buttons, I think it is not possible: unlike some other mouse (Rival 300,...) it does not emulate a keyboard, so this is not an hardware feature. Rivalcfg only support hardware feature of the mouse for now.

:)
