### ISSUE TITLE
Rival 110 colorshift (rgb) is it coming in the next update?

### ISSUE THREAD

**Issue by goodguylimz** [flozz/rivalcfg#81]

**Comment by flozz** [comment]
Hello, I forget to answer this issue, sorry...

The Rival 110 does not seem to support colorshift by hardware (it is a software feature of the SteelSeries Engine 3). So it will not be supported for that mouse.

Have a nice day :)

**Comment by ducknificient** [comment]
rival 110 support colorshift

**Comment by flozz** [comment]
@ducknificient As far as I know, this is not a feature supported by the hardware itself but a software feature of the SSE3 (it sends continuously command to the device to update the color).

But if you have info about hardware support of the colorshift on this device, please give me Bytes to configure this so I can implement it in Rivalcfg. :)

**Comment by ducknificient** [comment]
i see, thanks for the explanation..
