### ISSUE TITLE
Sensei 310 Support (1038:1722)

### ISSUE THREAD

**Issue by StarFscker** [flozz/rivalcfg#82]

**Comment by flozz** [comment]
Hum ok... Is it possible to have further information,

1. What is the mouse model (a link to the product page on an online shop can help)?
2. what's the problem with the mouse? It seems to not be supported by this application but maybe it is just a variation of an other model so it can be possible to support it?

Regards,

**Comment by StarFscker** [comment]
Sorry, thought I included it already, my bad. 

https://www.amazon.com/gp/product/B073WGB8G6/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&th=1

It's one of these, so it might be able to be supported just by adding a line for the 310 or something. 

Some commands I tried that were unsuccessful:

starfscker@blackbox: rivalcfg$ rivalcfg --version
3.6.0
starfscker@blackbox: rivalcfg$ rivalcfg -c
Usage: rivalcfg [options]

rivalcfg: error: no such option: -c
starfscker@blackbox: rivalcfg$ rivalcfg -c black
Usage: rivalcfg [options]

rivalcfg: error: no such option: -c
starfscker@blackbox: rivalcfg$ rivalcfg -C
Usage: rivalcfg [options]

rivalcfg: error: no such option: -C
starfscker@blackbox: rivalcfg$ rivalcfg -C black
Usage: rivalcfg [options]

rivalcfg: error: no such option: -C
starfscker@blackbox: rivalcfg$ rivalcfg --logo-color=black --wheel-color=black
Usage: rivalcfg [options]

rivalcfg: error: no such option: --logo-color
starfscker@blackbox: rivalcfg$ rivalcfg -l
SteelSeries Rival                                  1038:1384   
SteelSeries Rival 100                              1038:1702   
SteelSeries Rival 100 Dota 2 Edition               1038:170C   
SteelSeries Rival 110                              1038:1729   
SteelSeries Rival 300                              1038:1710   
Acer Predator Gaming Mouse (Rival 300)             1038:1714   
SteelSeries Rival 300 CS:GO Fade Edition           1038:1394   
SteelSeries Rival 300 CS:GO Hyperbeast Edition     1038:171A   
SteelSeries Rival 300 Dota 2 Edition               1038:1392   
SteelSeries Rival 300 HP Omen Edition              1038:1718   
SteelSeries Rival 310 (Experimental)               1038:1720   
SteelSeries Rival 500 (Experimental)               1038:170E   
SteelSeries Rival 600 (Experimental)               1038:1724   
SteelSeries Heroes of the Storm (Sensei Raw)       1038:1390   
SteelSeries Kana V2                                1038:137A   


Either I'm doing something wrong or the un-listed usbid is the cause

**Comment by flozz** [comment]
Oops sorry, I didn't saw it was in experimental support.

Only sensitivity options are supported for the Rival 310 yet. But the PR #43 adds supports for LEDs, so you can try this branch.

I have no time for this project currently, but I hope I will be able to work on it again by the end of the year :)

**Comment by StarFscker** [comment]
Hello, 

I tried the #43 changes and it allowed me to change the color of my LEDs to a pleasing yellow. 

Thank you very much.

**Comment by tobozo** [comment]
Sensei 310 Data Fragments

![image](https://user-images.githubusercontent.com/1893754/72908893-6ded0680-3d36-11ea-8f8d-348d74ea8837.png)

<details>
<summary><b>Effect: Steady</b> (color : #123456)</summary>
5b:00:00:10:27:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:00:00:00:00:00:00:00:01:12:34:56:12:34:56:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
</details>


<details>
<summary><b>Effect: ColorShift</b> (speed: 5.10s, pattern: 0%/33%/66%, color: #123456)</summary>
5b:00:00:ec:13:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:04:12:34:56:12:34:56:00:ff:ea:00:54:12:34:56:54:12:34:56:56:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
</details>


<details>
<summary><b>Effect: MultiColor Breathe</b> (speed: 5.10s, pattern: 45%, color : #123456)</summary>
5b:00:00:ec:13:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:03:12:34:56:12:34:56:3a:00:00:00:44:12:34:56:47:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
</details>


<details>
<summary><b>Effect: Trigger</b> (speed: 2s, rest color: #123456, active color : #654321)</summary>
5b:00:00:d0:07:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:00:00:00:07:00:00:00:02:65:43:21:65:43:21:00:12:34:56:ff:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
</details>


<details>
<summary><b>Effect: Disable illumination</b></summary>
5b:00:00:ec:13:00:00:00:00:00:00:00:00:00:00:00:00:00:00:01:00:00:00:00:00:00:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
</details>

Please specify what other captures you need and I'll be happy to add them

**Comment by tobozo** [comment]
# Sensei 310 Data Fragments

![image](https://user-images.githubusercontent.com/1893754/73312946-3eecfe00-422a-11ea-8137-9261909e7c5d.png)


<details>
<summary><b>Sensitivity 1 (CPI 1)</b> (value: 800)  
</summary>
53:00:01:07:00:42:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
</details>



![image](https://user-images.githubusercontent.com/1893754/73313091-94c1a600-422a-11ea-8f93-97d5d41207b5.png)

<details>
<summary><b>Sensitivity 2 (CPI 2)</b> (value: 1500)  
</summary>
53:00:02:0e:00:42:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
</details>



I didn't see any packet in Wireshark when fiddling with the buttons assignment options, maybe the mouse isn't aware of those settings.

![image](https://user-images.githubusercontent.com/1893754/73313485-ad7e8b80-422b-11ea-9fd0-0f616bd1a28e.png)

**Comment by FFY00** [comment]
The protocol for the Rival 310 has already been reverse engineered.

**Comment by tobozo** [comment]
@FFY00 I thought so too, but the last change on the [Sensei-310](https://github.com/flozz/rivalcfg/tree/sensei-310) branch was less than 24h ago so I guess there's still some fine tuning going on.

Since these captures have been requested by @flozz, there will be more updates and I apologize in advance for all the notifications this will generate.

**Comment by flozz** [comment]
Initial support of this mouse has been released in **rivalcfg v3.8.0** 😁️
