### ISSUE TITLE
Other Mice besides SteelSeries?

### ISSUE THREAD

**Issue by cj360** [flozz/rivalcfg#88]
Thoughts on possibly adding another mouse series outside SteelSeries to this project?
Since there is already a good amount of information on testing mice with this project I thought I might test the Glorious Model O when it arrives. 
This project was great for configuring my current steelseries mouse but it seems to be failing and the model seemed like a nice replacement apart from the windows only software.

**Comment by FFY00** [comment]
If you can provide dumps from the device I might be able to add support to https://github.com/libratbag/libratbag.

**Comment by flozz** [comment]
Hello, this project is dedicated to SteelSeries mice, but as @FFY00 said, there is the libratbag project that aims to support all gaming mice 🙂️

**Comment by flozz** [comment]
I close the issue, I hope that libratbag will help you :)
