### ISSUE TITLE
Cannot open mouse if not installed as root

### ISSUE THREAD

**Issue by VariableDeclared** [flozz/rivalcfg#90]
Hi, 

If rivalcfg is installed using the docs recommended method of

```
pip install rivalcfg
```

The app will fail to open the mouse. Although if it is installed using sudo it works fine, although requires being elevated (sudoed) when configuring the mouse.

Distribution: Ubuntu 19.10.

Thank you for your awesome work!

**Comment by flozz** [comment]
Hello,

When rivalcfg is not installed as root, the udev rules cannot be installed so there is permission issue. But you can fix it after the installation : https://github.com/flozz/rivalcfg#i-have-a-permission-denied-error-what-can-i-do 

😃️

**Comment by VariableDeclared** [comment]
Hey @flozz.

I don't believe this is the message I was seeing, I saw another issue which annoyingly I can't repeat by installing with non-root.

I believe it was this error: https://github.com/flozz/rivalcfg/blob/6d7d9e7a39ce7366e2f1c6b42e5b672f01c8b963/rivalcfg/__main__.py#L22

**Comment by flozz** [comment]
This message can be caused by a busy device... sometime it is sufficient to unplug/replug the mouse to the computer to fix. And sometime it is a permission issue ^^'

**Comment by VariableDeclared** [comment]
OK, thank you for that, I believe we have documented this even here, if anyone else hits the same issue.

So i'll close this issue, thanks again for your work!
