### ISSUE TITLE
Rival 300s

### ISSUE THREAD

**Issue by imm21** [flozz/rivalcfg#92]
Is there a chance will have support Rival 300s? Thanks.

**Comment by flozz** [comment]
Maybe. If it works like the Rival 300, it will be easy, else someone will have to make some reverse engineering on it.

First of all, can you tel me what is the product_id of the mouse. you can find it with the following command:

    lsusb | grep SteelSeries

**Comment by imm21** [comment]
Would be great! 

`Bus 001 Device 004: ID 1038:1810 SteelSeries ApS SteelSeries Rival 300S Gaming Mouse`

**Comment by flozz** [comment]
If I make a test branch, will you be able to check if everything work? :)

**Comment by imm21** [comment]
I can try :)

**Comment by flozz** [comment]
I made a test branch.

To test it, you first have to remove any installed rivalcfg version. Then

* install the required dependencies:

      apt-get install build-essential python-dev libusb-1.0-0-dev libudev-dev git python-pip

* clone this repository:

      git clone https://github.com/flozz/rivalcfg

* go to the cloned folder:

      cd rivalcfg

* and checkout the test branch:

      git checkout rival-300s

* finally install the software:

      sudo pip install .

Now you should have the right rivalcfg version installed, you can test it.

First check the mouse is detected:

    rivalcfg -l

You should see the following line:

    SteelSeries Rival 300s                             1038:1810   (plugged)
    
Then you can list all available command using

    rivalcfg -h

And you can test them all to check if everything work.

**Comment by imm21** [comment]
SteelSeries Rival 300s                             1038:1810   (plugged)

So sad but it changes nothing, no sens no colors. I tried with sudo and without. :(

**Comment by flozz** [comment]
Ok... this means that this mouse has nothing in common with the Rival 300...

So the only way to support it is to reverse engineer it...

I wrote [an article about reverse engineering mice](https://blog.flozz.fr/2016/03/27/steelseries-rival-100-reverse-engineering-dun-peripherique-usb/) so if someone want to try... The article is in French but Google Translate should help.

**Comment by imm21** [comment]
Ok, i will try use it. Thank you!

**Comment by flozz** [comment]
I had more info on this device. I added its support on `master`, can someone try it? :)
