### ISSUE TITLE
rivalcfg not installed properly on OpenSUSE

### ISSUE THREAD

**Issue by Frambooisier** [flozz/rivalcfg#93]
The out put of rivalcfg -l is:
flap@SFX:~> rivalcfg -l Traceback (most recent call last): File "/usr/local/bin/rivalcfg", line 6, in <module> from pkg_resources import load_entry_point File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3250, in <module> @_call_aside File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside f(*args, **kwargs) File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set working_set = WorkingSet._build_master() File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master ws.require(__requires__) File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require needed = self.resolve(parse_requirements(requirements)) File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve raise DistributionNotFound(req, requirers) pkg_resources.DistributionNotFound: The 'hidapi>=0.7.99.post20' distribution was not found and is required by rivalcfg

**Comment by flozz** [comment]
continuation of https://github.com/andrepl/rivalctl/issues/9

**Comment by flozz** [comment]
Hello,

it seems that the `hidapi` dependency is not installed. On latest Ubuntu distributions you can try 

```
sudo apt install python-hid
```

else you can install it using `pip`:

```
sudo pip install hidapi
```

**Comment by Frambooisier** [comment]
Hello,

I'm on the Open suse tumbleweed, installing package below allowed me to run your second suggested command successfully since zypper can't find "python-hid"
```
sudo zypper in libhidapi-devel 
```
that resulted in:
```
The following 4 NEW packages are going to be installed:
  libhidapi-devel libhidapi-hidraw0 libhidapi-libusb0 libusb-1_0-devel
```
(I don't really know what I am installing I just look for things that have a similar name to the requested package and install it)

```
sudo pip install hidapi
 sudo pip install hidapi
Collecting hidapi
  Using cached https://files.pythonhosted.org/packages/c1/86/89df0e8890f96eeb5fb68d4ccb14cb38e2c2d2cfd7601ba972206acd9015/hidapi-0.7.99.post21.tar.gz
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3.7/site-packages (from hidapi) (41.6.0)
Installing collected packages: hidapi
    Running setup.py install for hidapi ... done
Successfully installed hidapi-0.7.99.post21
```

Now output of rivalcfg -l:

```
flap@SFX:~> rivalcfg -l
Traceback (most recent call last):
  File "/usr/local/bin/rivalcfg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'hidapi>=0.7.99.post20' distribution was not found and is required by rivalcfg
```

**Comment by flozz** [comment]
It is strange... I do not know OpenSuze at all... I will try to reproduce in a VM

**Comment by flozz** [comment]
Ow, it seems that OpenSUSE use python3 by default in some cases. This may explain your issue. Please try to install `hidapi` using `pip3`:

    sudo pip3 install hidapi

**Comment by Frambooisier** [comment]
`sudo pip3 install hidapi`
results in:
`sudo pip3 install hidapi
Requirement already satisfied: hidapi in /usr/lib64/python3.7/site-packages (0.7.99.post21)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3.7/site-packages (from hidapi) (41.6.0)
`
rivalcfg -l output has not changed.

**Comment by flozz** [comment]
hum...

Can you try 

    sudo pip3 install rivalcfg

and then

    python3 -m rivalcfg -l

does it work?

**Comment by Frambooisier** [comment]
It did work yay!

`sudo pip3 install rivalcfg
[sudo] password for root: 
Collecting rivalcfg
  Downloading https://files.pythonhosted.org/packages/d8/5b/2223cc3983c5216ad8e52e1f78b457d0bd0f9870f5050194c1fb0163f216/rivalcfg-3.7.0.tar.gz
Requirement already satisfied: hidapi>=0.7.99.post20 in /usr/lib64/python3.7/site-packages (from rivalcfg) (0.7.99.post21)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3.7/site-packages (from hidapi>=0.7.99.post20->rivalcfg) (41.6.0)
Installing collected packages: rivalcfg
    Running setup.py install for rivalcfg ... done
Successfully installed rivalcfg-3.7.0
flap@SFX:~> python3 -m rivalcfg -l
SteelSeries Rival                                  1038:1384   
SteelSeries Rival 100                              1038:1702   
SteelSeries Rival 100 Dota 2 Edition               1038:170C   
SteelSeries Rival 110                              1038:1729   
SteelSeries Rival 300                              1038:1710   
Acer Predator Gaming Mouse (Rival 300)             1038:1714   
SteelSeries Rival 300 CS:GO Fade Edition           1038:1394   
SteelSeries Rival 300 CS:GO Hyperbeast Edition     1038:171A   
SteelSeries Rival 300 Dota 2 Edition               1038:1392   
SteelSeries Rival 300 HP Omen Edition              1038:1718   
SteelSeries Rival 310 (Experimental)               1038:1720   
SteelSeries Rival 500 (Experimental)               1038:170E   
SteelSeries Rival 600 (Experimental)               1038:1724   
SteelSeries Rival 710 (Experimental)               1038:1730   
SteelSeries Heroes of the Storm (Sensei Raw)       1038:1390   
SteelSeries Kana V2                                1038:137A   
`

**Comment by flozz** [comment]
rivalcfg seems to work now, but you mouse is not recognized... what is the exact model of you mouse?

**Comment by Frambooisier** [comment]
It's because it was not connected to the pc, I tested it now and it works. I have Rival 100 and I could change the dpi and color. Thank you! Can you explain to me what was the problem (in simple words)?

**Comment by flozz** [comment]
Ok cool if it work.

I do not really know what is the problem with your OS, but it seems that the `hidapi` package was not properly installed for Python 2.7 (I do not know why). But is was successfully installed for Python 3.x (using pip3). So when you do `python3 -m rivalcfg`, you run rivalcfg using Python 3 and it works :)
