### ISSUE TITLE
Last colorshift position too high

### ISSUE THREAD

**Issue by uglynewt** [flozz/rivalcfg#96]
I've been using `rivalcfg` (with a Sensei 310) and I've noticed that the rgbshift sequence tends to "jump" back to the start, rather than completing the loop.  I found that the last position sent (the one automatically added, to smooth the ending) is always 0xff, regardless of the total of previous values.

The problem is in [rgbuniversal_handler](https://github.com/flozz/rivalcfg/blob/master/rivalcfg/command_handlers.py#L96):

     positions = map(lambda x: int(x, 16), positions)

`map` provides an iterator, which is exhausted the first time `positions` is used (by `zip`).  So the calls to `sum(positions)` return 0 each time.

Changing that line to

     positions = list(map(lambda x: int(x, 16), positions))

fixed it for me.

**Comment by flozz** [comment]
Hello,

First I was unable to reproduce, but it was because I tested with python 2.7 (I know it is deprecated but it still the default interpreter on my distro...). With Python 3.x you're right, `map()` returns a generator.

Thanks for the report ! :+1:

**Comment by flozz** [comment]
Fix released in **rivalcfg v3.9.0**
